type Copy = Record<string, { id: string; en: string }>;
const same = (value: string) => ({ id: value, en: value });

/** Every Reporting string, intentionally in both Backoffice languages. */
export const reportingCopy: Copy = {
  // Page and report catalog
  Reporting: { id: 'Pelaporan', en: 'Reporting' },
  Reports: { id: 'Laporan', en: 'Reports' },
  'Business reports from recorded sales, workforce, and finance activity.': {
    id: 'Laporan bisnis dari penjualan, karyawan, dan aktivitas keuangan yang tercatat.',
    en: 'Business reports from recorded sales, workforce, and finance activity.',
  },
  'Business Performance': { id: 'Ringkasan Kinerja Bisnis', en: 'Business Performance' },
  'Transaction Report': { id: 'Laporan Transaksi', en: 'Transaction Report' },
  'Catalog Performance': { id: 'Kinerja Katalog', en: 'Catalog Performance' },
  'Component Usage': { id: 'Pemakaian Komponen', en: 'Component Usage' },
  'Product Commission': { id: 'Komisi Produk', en: 'Product Commission' },
  'Employee Performance': { id: 'Kinerja Karyawan', en: 'Employee Performance' },
  'Attendance Report': { id: 'Laporan Absensi', en: 'Attendance Report' },
  'Payment Report': { id: 'Laporan Pembayaran', en: 'Payment Report' },
  'Expense Report': { id: 'Laporan Pengeluaran', en: 'Expense Report' },
  'Cash Movement': { id: 'Pergerakan Kas', en: 'Cash Movement' },
  'Tax Report': { id: 'Laporan Pajak', en: 'Tax Report' },
  'Location Performance': { id: 'Kinerja Lokasi', en: 'Location Performance' },

  // Controls
  'Report & period': { id: 'Laporan & periode', en: 'Report & period' },
  'Report type': { id: 'Jenis laporan', en: 'Report type' },
  Period: { id: 'Periode', en: 'Period' },
  Location: { id: 'Lokasi', en: 'Location' },
  'All locations': { id: 'Semua lokasi', en: 'All locations' },
  'Select location': { id: 'Pilih lokasi', en: 'Select location' },
  'Choose a location to see this report.': {
    id: 'Pilih lokasi untuk melihat laporan ini.',
    en: 'Choose a location to see this report.',
  },
  All: { id: 'Semua', en: 'All' },
  Export: { id: 'Ekspor', en: 'Export' },
  'Excel (.xlsx)': same('Excel (.xlsx)'),
  'CSV (.csv)': same('CSV (.csv)'),
  'Could not export this report.': {
    id: 'Laporan ini tidak dapat diekspor.',
    en: 'Could not export this report.',
  },
  'Reset filters': { id: 'Atur ulang filter', en: 'Reset filters' },
  records: { id: 'data', en: 'records' },
  'Search transaction or invoice number': {
    id: 'Cari nomor transaksi atau faktur',
    en: 'Search transaction or invoice number',
  },
  'Search component or service': {
    id: 'Cari komponen atau layanan',
    en: 'Search component or service',
  },
  'Search transaction, employee, or product': {
    id: 'Cari transaksi, karyawan, atau produk',
    en: 'Search transaction, employee, or product',
  },
  'Search employee code or name': {
    id: 'Cari kode atau nama karyawan',
    en: 'Search employee code or name',
  },

  // States
  'Could not load this report.': {
    id: 'Laporan ini tidak dapat dimuat.',
    en: 'Could not load this report.',
  },
  'Try again': { id: 'Coba lagi', en: 'Try again' },
  'No report data is available for this period.': {
    id: 'Belum ada data laporan untuk periode ini.',
    en: 'No report data is available for this period.',
  },
  'Detailed records': { id: 'Rincian data', en: 'Detailed records' },
  'Records for the selected report, period, and filters.': {
    id: 'Data untuk laporan, periode, dan filter yang dipilih.',
    en: 'Records for the selected report, period, and filters.',
  },
  'View detail': { id: 'Lihat detail', en: 'View detail' },
  Close: { id: 'Tutup', en: 'Close' },
  Total: same('Total'),
  'data points': { id: 'titik data', en: 'data points' },
  'Selected period': { id: 'Periode terpilih', en: 'Selected period' },

  // KPIs
  Revenue: { id: 'Pendapatan', en: 'Revenue' },
  Transactions: { id: 'Transaksi', en: 'Transactions' },
  'Average transaction': { id: 'Rata-rata transaksi', en: 'Average transaction' },
  'Items sold': { id: 'Item terjual', en: 'Items sold' },
  'Approved expenses': { id: 'Pengeluaran disetujui', en: 'Approved expenses' },
  'Net revenue': { id: 'Pendapatan bersih', en: 'Net revenue' },
  'Payments received': { id: 'Pembayaran diterima', en: 'Payments received' },
  'Items with sales': { id: 'Item terjual (jenis)', en: 'Items with sales' },
  Components: { id: 'Komponen', en: 'Components' },
  Usages: { id: 'Pemakaian', en: 'Usages' },
  'Billed additions': { id: 'Tambahan ditagihkan', en: 'Billed additions' },
  'Net commission': { id: 'Komisi bersih', en: 'Net commission' },
  'Commission earned': { id: 'Komisi diperoleh', en: 'Commission earned' },
  'Commission reversed': { id: 'Komisi dibatalkan', en: 'Commission reversed' },
  'Units sold': { id: 'Unit terjual', en: 'Units sold' },
  'Contribution revenue': { id: 'Pendapatan kontribusi', en: 'Contribution revenue' },
  Employees: { id: 'Karyawan', en: 'Employees' },
  'Items worked': { id: 'Item dikerjakan', en: 'Items worked' },
  Records: { id: 'Data', en: 'Records' },
  'Net received': { id: 'Diterima bersih', en: 'Net received' },
  'Successful payments': { id: 'Pembayaran berhasil', en: 'Successful payments' },
  Refunded: { id: 'Dikembalikan', en: 'Refunded' },
  'Failed attempts': { id: 'Percobaan gagal', en: 'Failed attempts' },
  Expenses: { id: 'Pengeluaran', en: 'Expenses' },
  'Net movement': { id: 'Pergerakan bersih', en: 'Net movement' },
  Movements: { id: 'Pergerakan', en: 'Movements' },
  'Taxable base': { id: 'Dasar pengenaan pajak', en: 'Taxable base' },
  Tax: { id: 'Pajak', en: 'Tax' },
  'Tax included in price': { id: 'Pajak termasuk harga', en: 'Tax included in price' },
  'Tax added to price': { id: 'Pajak ditambahkan ke harga', en: 'Tax added to price' },
  'Locations with sales': { id: 'Lokasi dengan penjualan', en: 'Locations with sales' },

  // Analytics
  'Revenue trend': { id: 'Tren pendapatan', en: 'Revenue trend' },
  'Payment mix': { id: 'Komposisi pembayaran', en: 'Payment mix' },
  'Transaction revenue': { id: 'Pendapatan transaksi', en: 'Transaction revenue' },
  'Payment method mix': { id: 'Komposisi metode pembayaran', en: 'Payment method mix' },
  'Revenue by transaction status': {
    id: 'Pendapatan per status transaksi',
    en: 'Revenue by transaction status',
  },
  'Top items by revenue': { id: 'Item teratas per pendapatan', en: 'Top items by revenue' },
  'Usage activity': { id: 'Aktivitas pemakaian', en: 'Usage activity' },
  'Usage source': { id: 'Sumber pemakaian', en: 'Usage source' },
  'Most used components': { id: 'Komponen paling banyak dipakai', en: 'Most used components' },
  'Net commission by employee': {
    id: 'Komisi bersih per karyawan',
    en: 'Net commission by employee',
  },
  'Top contributors': { id: 'Kontributor teratas', en: 'Top contributors' },
  'Attendance records': { id: 'Catatan absensi', en: 'Attendance records' },
  'Attendance status': { id: 'Status absensi', en: 'Attendance status' },
  'Recorded expenses': { id: 'Pengeluaran tercatat', en: 'Recorded expenses' },
  'Expenses by status': { id: 'Pengeluaran per status', en: 'Expenses by status' },
  'Cash in and out': { id: 'Kas masuk dan keluar', en: 'Cash in and out' },
  'Tax collected': { id: 'Pajak terkumpul', en: 'Tax collected' },
  'Tax by tax code': { id: 'Pajak per kode pajak', en: 'Tax by tax code' },
  'Tax by item': { id: 'Pajak per item', en: 'Tax by item' },
  'Revenue by location': { id: 'Pendapatan per lokasi', en: 'Revenue by location' },
  'No analytics data is available for this period.': {
    id: 'Belum ada data analitik untuk periode ini.',
    en: 'No analytics data is available for this period.',
  },
  'Usage by component': { id: 'Pemakaian per komponen', en: 'Usage by component' },
  'Quantities recorded at the time of each transaction. Billed amounts are part of the sold line, not extra revenue or cost.':
    {
      id: 'Jumlah tercatat saat setiap transaksi. Nilai yang ditagihkan adalah bagian dari item terjual, bukan pendapatan atau biaya tambahan.',
      en: 'Quantities recorded at the time of each transaction. Billed amounts are part of the sold line, not extra revenue or cost.',
    },
  'Total used': { id: 'Total dipakai', en: 'Total used' },
  Configured: { id: 'Terkonfigurasi', en: 'Configured' },
  Selected: { id: 'Dipilih', en: 'Selected' },
  'Billed amount': { id: 'Nilai ditagihkan', en: 'Billed amount' },
  'Used by service': { id: 'Dipakai oleh layanan', en: 'Used by service' },

  // Filters and columns
  'Transaction status': { id: 'Status transaksi', en: 'Transaction status' },
  'Payment method': { id: 'Metode pembayaran', en: 'Payment method' },
  'Payment status': { id: 'Status pembayaran', en: 'Payment status' },
  'Work status': { id: 'Status pengerjaan', en: 'Work status' },
  'Item type': { id: 'Jenis item', en: 'Item type' },
  'Catalog status': { id: 'Status katalog', en: 'Catalog status' },
  Category: { id: 'Kategori', en: 'Category' },
  Item: same('Item'),
  'Item code': { id: 'Kode item', en: 'Item code' },
  Summary: { id: 'Ringkasan', en: 'Summary' },
  Component: { id: 'Komponen', en: 'Component' },
  Service: { id: 'Layanan', en: 'Service' },
  'Entry type': { id: 'Jenis catatan', en: 'Entry type' },
  Employee: { id: 'Karyawan', en: 'Employee' },
  Product: { id: 'Produk', en: 'Product' },
  'Employee status': { id: 'Status karyawan', en: 'Employee status' },
  Source: { id: 'Sumber', en: 'Source' },
  Position: { id: 'Jabatan', en: 'Position' },
  Status: same('Status'),
  Origin: { id: 'Asal', en: 'Origin' },
  'Source account': { id: 'Sumber dana', en: 'Source account' },
  Direction: { id: 'Arah', en: 'Direction' },
  'Financial account': { id: 'Akun keuangan', en: 'Financial account' },
  'Location status': { id: 'Status lokasi', en: 'Location status' },
  Date: { id: 'Tanggal', en: 'Date' },
  Transaction: { id: 'Transaksi', en: 'Transaction' },
  '#': same('#'),
  Quantity: { id: 'Jumlah', en: 'Quantity' },
  Discount: { id: 'Diskon', en: 'Discount' },
  'Average value': { id: 'Nilai rata-rata', en: 'Average value' },
  Used: { id: 'Dipakai', en: 'Used' },
  Billed: { id: 'Ditagihkan', en: 'Billed' },
  Entry: { id: 'Catatan', en: 'Entry' },
  Commission: { id: 'Komisi', en: 'Commission' },
  'Average per transaction': { id: 'Rata-rata per transaksi', en: 'Average per transaction' },
  'Top item': { id: 'Item teratas', en: 'Top item' },
  'Check-in': { id: 'Masuk', en: 'Check-in' },
  'Check-out': { id: 'Pulang', en: 'Check-out' },
  Note: { id: 'Catatan', en: 'Note' },
  Method: { id: 'Metode', en: 'Method' },
  Amount: { id: 'Jumlah', en: 'Amount' },
  Description: { id: 'Deskripsi', en: 'Description' },
  'From expense': { id: 'Dari pengeluaran', en: 'From expense' },
  Treatment: { id: 'Perlakuan', en: 'Treatment' },

  // Enumerated values
  Open: { id: 'Berjalan', en: 'Open' },
  Completed: { id: 'Selesai', en: 'Completed' },
  Cancelled: { id: 'Dibatalkan', en: 'Cancelled' },
  Reversed: { id: 'Direversal', en: 'Reversed' },
  Pending: { id: 'Menunggu', en: 'Pending' },
  Succeeded: { id: 'Berhasil', en: 'Succeeded' },
  Failed: { id: 'Gagal', en: 'Failed' },
  Expired: { id: 'Kedaluwarsa', en: 'Expired' },
  Cash: { id: 'Tunai', en: 'Cash' },
  'Bank transfer': { id: 'Transfer bank', en: 'Bank transfer' },
  'E-wallet': { id: 'Dompet digital', en: 'E-wallet' },
  QRIS: same('QRIS'),
  Payment: { id: 'Pembayaran', en: 'Payment' },
  Refund: { id: 'Pengembalian dana', en: 'Refund' },
  Waiting: { id: 'Menunggu', en: 'Waiting' },
  'In progress': { id: 'Dikerjakan', en: 'In progress' },
  Draft: same('Draft'),
  Active: { id: 'Aktif', en: 'Active' },
  Inactive: { id: 'Nonaktif', en: 'Inactive' },
  Archived: { id: 'Diarsipkan', en: 'Archived' },
  Present: { id: 'Hadir', en: 'Present' },
  Absent: { id: 'Tidak hadir', en: 'Absent' },
  Leave: { id: 'Cuti', en: 'Leave' },
  Sick: { id: 'Sakit', en: 'Sick' },
  'Recorded here': { id: 'Dicatat di sini', en: 'Recorded here' },
  HRIS: same('HRIS'),
  Approved: { id: 'Disetujui', en: 'Approved' },
  Rejected: { id: 'Ditolak', en: 'Rejected' },
  Backoffice: same('Backoffice'),
  Operational: { id: 'Operasional', en: 'Operational' },
  'Cash in': { id: 'Kas masuk', en: 'Cash in' },
  'Cash out': { id: 'Kas keluar', en: 'Cash out' },
  'Configured component': { id: 'Komponen terkonfigurasi', en: 'Configured component' },
  'Selected during transaction': {
    id: 'Dipilih saat transaksi',
    en: 'Selected during transaction',
  },
  'Service default': { id: 'Bawaan layanan', en: 'Service default' },
  'Service variant': { id: 'Varian layanan', en: 'Service variant' },
  'Commission reversal': { id: 'Pembatalan komisi', en: 'Commission reversal' },
  'Fixed per unit': { id: 'Tetap per unit', en: 'Fixed per unit' },
  'Included in price': { id: 'Termasuk dalam harga', en: 'Included in price' },
  'Added to price': { id: 'Ditambahkan ke harga', en: 'Added to price' },
  Yes: { id: 'Ya', en: 'Yes' },
  No: { id: 'Tidak', en: 'No' },

  // Detail dialogs
  Invoice: { id: 'Faktur', en: 'Invoice' },
  'Occurred at': { id: 'Waktu', en: 'Occurred at' },
  Variant: { id: 'Varian', en: 'Variant' },
  'Component usage detail': { id: 'Detail pemakaian komponen', en: 'Component usage detail' },
  'Parent service': { id: 'Layanan induk', en: 'Parent service' },
  Usage: { id: 'Pemakaian', en: 'Usage' },
  'Quantity per unit': { id: 'Jumlah per unit', en: 'Quantity per unit' },
  'Service quantity': { id: 'Jumlah layanan', en: 'Service quantity' },
  'Selling unit price': { id: 'Harga jual per unit', en: 'Selling unit price' },
  'Billed addition': { id: 'Tambahan ditagihkan', en: 'Billed addition' },
  'Included with the service, not billed separately.': {
    id: 'Termasuk dalam layanan, tidak ditagihkan terpisah.',
    en: 'Included with the service, not billed separately.',
  },
  'Commission detail': { id: 'Detail komisi', en: 'Commission detail' },
  'Commission type': { id: 'Jenis komisi', en: 'Commission type' },
  'Commission per unit': { id: 'Komisi per unit', en: 'Commission per unit' },
  'Commission amount': { id: 'Jumlah komisi', en: 'Commission amount' },
  'This entry reverses commission earned earlier for this sale.': {
    id: 'Catatan ini membatalkan komisi yang diperoleh sebelumnya untuk penjualan ini.',
    en: 'This entry reverses commission earned earlier for this sale.',
  },
  'Payment detail': { id: 'Detail pembayaran', en: 'Payment detail' },
  'Refund detail': { id: 'Detail pengembalian dana', en: 'Refund detail' },
  Account: { id: 'Akun', en: 'Account' },
  'Cash received': { id: 'Uang diterima', en: 'Cash received' },
  Change: { id: 'Kembalian', en: 'Change' },
  'Provider reference': { id: 'Referensi penyedia', en: 'Provider reference' },
  'Completed at': { id: 'Selesai pada', en: 'Completed at' },
  'This refund returns money from an earlier successful payment of this transaction.': {
    id: 'Pengembalian dana ini mengembalikan uang dari pembayaran berhasil sebelumnya pada transaksi ini.',
    en: 'This refund returns money from an earlier successful payment of this transaction.',
  },
  'Tax detail': { id: 'Detail pajak', en: 'Tax detail' },
  'Tax code': { id: 'Kode pajak', en: 'Tax code' },
  'Tax name': { id: 'Nama pajak', en: 'Tax name' },
  Rate: { id: 'Tarif', en: 'Rate' },
  'Tax amount': { id: 'Jumlah pajak', en: 'Tax amount' },
  'Tax included': { id: 'Pajak termasuk', en: 'Tax included' },
  'Tax added': { id: 'Pajak ditambahkan', en: 'Tax added' },

  // Actors
  'Created by': { id: 'Dibuat oleh', en: 'Created by' },
  'Processed by': { id: 'Diproses oleh', en: 'Processed by' },
  'Recorded by': { id: 'Dicatat oleh', en: 'Recorded by' },
  'Decided by': { id: 'Diputuskan oleh', en: 'Decided by' },
  'Updated by': { id: 'Diperbarui oleh', en: 'Updated by' },
  'Settled by': { id: 'Diselesaikan oleh', en: 'Settled by' },
  System: { id: 'Sistem', en: 'System' },
  'Account unavailable': { id: 'Akun tidak tersedia', en: 'Account unavailable' },

  // Employee performance detail
  'Employee performance detail': {
    id: 'Detail kinerja karyawan',
    en: 'Employee performance detail',
  },
  'Could not load this employee’s contribution.': {
    id: 'Kontribusi karyawan ini tidak dapat dimuat.',
    en: 'Could not load this employee’s contribution.',
  },
  'Loading contribution…': { id: 'Memuat kontribusi…', en: 'Loading contribution…' },
  'Check the connection and try again.': {
    id: 'Periksa koneksi lalu coba lagi.',
    en: 'Check the connection and try again.',
  },
  'Current position': { id: 'Jabatan saat ini', en: 'Current position' },
  'Rank in this period': { id: 'Peringkat periode ini', en: 'Rank in this period' },
  'Contribution trend': { id: 'Tren kontribusi', en: 'Contribution trend' },
  'Contribution by service': { id: 'Kontribusi per layanan', en: 'Contribution by service' },
  transactions: { id: 'transaksi', en: 'transactions' },
  'work items': { id: 'item kerja', en: 'work items' },
  'Main service': { id: 'Layanan utama', en: 'Main service' },
  'Additional item': { id: 'Item tambahan', en: 'Additional item' },
  'No contribution was recorded in this period.': {
    id: 'Belum ada kontribusi tercatat pada periode ini.',
    en: 'No contribution was recorded in this period.',
  },
  'Contribution records': { id: 'Rincian kontribusi', en: 'Contribution records' },
  Work: { id: 'Pekerjaan', en: 'Work' },
  Contribution: { id: 'Kontribusi', en: 'Contribution' },
  'Transaction detail': { id: 'Detail transaksi', en: 'Transaction detail' },
  'This record’s detail is not available. Refresh the report and try again.': {
    id: 'Detail data ini tidak tersedia. Muat ulang laporan lalu coba lagi.',
    en: 'This record’s detail is not available. Refresh the report and try again.',
  },
  'This export has too many records. Narrow the period or filters.': {
    id: 'Data ekspor terlalu banyak. Persempit periode atau filter.',
    en: 'This export has too many records. Narrow the period or filters.',
  },
};
