import { useBackofficeLocalization } from '../../app/localization/backoffice-localization';

const messages = {
  id: {
    title: 'Diskon & promo',
    description:
      'Atur promo otomatis dan kode promo yang diterapkan pada transaksi yang memenuhi syarat.',
    add: 'Tambah promo',
    edit: 'Ubah promo',
    newBadge: 'Baru',
    informationStep: 'Informasi & Nilai Diskon',
    targetStep: 'Cakupan & Target Item',
    promotionInfo: 'Informasi Promo',
    cashierVisibility: 'Tampil di kasir POS',
    operationalStatus: 'Status Operasional',
    operationalStatusHint: 'Promo aktif & dapat digunakan di kasir.',
    termsAndDiscount: 'Ketentuan & Nilai Diskon',
    percentageCard: 'Diskon Persentase (%)',
    percentageCardHint: 'Potongan harga dihitung berdasarkan persentase.',
    fixedCard: 'Nominal Tetap (Rp)',
    fixedCardHint: 'Potongan harga menggunakan nominal rupiah pasti.',
    scopePromo: 'Cakupan Promo',
    allTransactions: 'Semua Transaksi',
    allTransactionsHint: 'Seluruh nota transaksi.',
    perCategory: 'Per Kategori',
    perCategoryHint: 'Kategori tertentu.',
    perItemVariant: 'Per Item & Varian',
    perItemVariantHint: 'Item atau varian khusus.',
    targetItems: 'Target Item Induk',
    selectedActive: 'item aktif dipilih',
    allItems: 'Semua Item',
    activeShort: 'Aktif',
    defaultLocked: 'Default / Terkunci',
    currencyLocked: 'Mata uang default bisnis, terkunci',
    maximumPlaceholder: 'Contoh: 50.000',
    minimumPlaceholder: 'Contoh: 100.000',
    addItem: 'Tambah Item',
    specificVariants: 'Varian Spesifik',
    includedViaParent: 'Termasuk dari item induk',
    notIncluded: 'Tidak Termasuk',
    deletePromotion: 'Hapus Promo',
    deleteUnavailable:
      'Penghapusan permanen belum tersedia. Nonaktifkan promo melalui Status Operasional.',
    requiredHint: '* Wajib diisi',
    savePromotion: 'Simpan Promo',
    saveChanges: 'Simpan Perubahan',
    parentIncludesVariants: 'Item induk mencakup seluruh variannya.',
    selectedCategoriesAllItems: 'Terapkan ke semua item pada kategori terpilih',
    targetWorkspaceHint:
      'Pilih item induk untuk mencakup semua varian, atau pilih varian tertentu.',
    namePlaceholder: 'Contoh: Promo Diskon Kilat',
    automaticCodeHint: 'OPSIONAL JIKA OTOMATIS',
    name: 'Nama',
    mode: 'Cara penerapan',
    automatic: 'Otomatis',
    code: 'Kode promo',
    codeLabel: 'Kode',
    scope: 'Cakupan',
    item: 'Item',
    variants: 'Varian tertentu',
    variantHint:
      'Target item induk berlaku untuk semua varian. Pilih varian tertentu untuk membatasi promo.',
    category: 'Kategori',
    transaction: 'Transaksi',
    discountType: 'Jenis diskon',
    percentage: 'Persentase',
    fixed: 'Nominal',
    value: 'Nilai diskon',
    currency: 'Mata uang',
    currencyHint: 'Wajib untuk diskon nominal, maksimum diskon, atau minimum pembelian.',
    maximum: 'Maksimum diskon',
    minimum: 'Minimum pembelian',
    effectiveFrom: 'Mulai berlaku',
    effectiveUntil: 'Berakhir',
    effectivity: 'Periode',
    locations: 'Lokasi',
    targets: 'Target',
    allLocations: 'Semua lokasi',
    categoryItemScope: 'Item dalam kategori',
    allCategoryItems: 'Semua item dalam kategori',
    selectedCategoryItems: 'Item tertentu saja',
    selectCategoryItems: 'Pilih item yang mendapat promo',
    noCategoryItems: 'Tidak ada item aktif pada kategori yang dipilih.',
    enabled: 'Aktif',
    status: 'Status',
    active: 'Aktif',
    scheduled: 'Terjadwal',
    expired: 'Berakhir',
    disabled: 'Nonaktif',
    noEnd: 'Tanpa batas akhir',
    immediate: 'Langsung',
    save: 'Simpan',
    cancel: 'Batal',
    empty: 'Belum ada diskon atau promo.',
    saved: 'Promo disimpan.',
    saveFailed: 'Promo tidak dapat disimpan.',
    invalid: 'Periksa kembali data promo.',
    selectTarget: 'Pilih minimal satu target.',
    optional: 'Opsional',
    percentageHint: 'Masukkan persentase, misalnya 10 untuk 10%.',
    fixedHint: 'Masukkan nominal sesuai mata uang yang dipilih.',
    selected: 'dipilih',
    all: 'Semua',
    noOptions: 'Tidak ada pilihan aktif.',
    targetSummary: 'Target',
    discount: 'Diskon',
    forbidden: 'Anda tidak memiliki izin untuk mengubah promo.',
    serverError: 'Layanan promo sedang bermasalah. Coba lagi.',
  },
  en: {
    title: 'Discounts & promotions',
    description: 'Manage automatic promotions and promo codes applied to eligible transactions.',
    add: 'Add promotion',
    edit: 'Edit promotion',
    newBadge: 'New',
    informationStep: 'Information & Discount',
    targetStep: 'Scope & Item Targets',
    promotionInfo: 'Promotion Information',
    cashierVisibility: 'Shown in POS cashier',
    operationalStatus: 'Operational Status',
    operationalStatusHint: 'Promotion is active and can be used at the cashier.',
    termsAndDiscount: 'Terms & Discount Value',
    percentageCard: 'Percentage Discount (%)',
    percentageCardHint: 'The price reduction is calculated as a percentage.',
    fixedCard: 'Fixed Amount',
    fixedCardHint: 'The price reduction uses a fixed currency amount.',
    scopePromo: 'Promotion Scope',
    allTransactions: 'All Transactions',
    allTransactionsHint: 'Every transaction receipt.',
    perCategory: 'By Category',
    perCategoryHint: 'Selected categories.',
    perItemVariant: 'By Item & Variant',
    perItemVariantHint: 'Specific items or variants.',
    targetItems: 'Parent Item Targets',
    selectedActive: 'active items selected',
    allItems: 'All Items',
    activeShort: 'Active',
    defaultLocked: 'Default / Locked',
    currencyLocked: 'Default business currency, locked',
    maximumPlaceholder: 'Example: 50,000',
    minimumPlaceholder: 'Example: 100,000',
    addItem: 'Add Item',
    specificVariants: 'Specific Variants',
    includedViaParent: 'Included by parent item',
    notIncluded: 'Not Included',
    deletePromotion: 'Delete Promotion',
    deleteUnavailable:
      'Permanent deletion is not available. Disable the promotion using Operational Status.',
    requiredHint: '* Required',
    savePromotion: 'Save Promotion',
    saveChanges: 'Save Changes',
    parentIncludesVariants: 'The parent item includes all of its variants.',
    selectedCategoriesAllItems: 'Apply to every item in selected categories',
    targetWorkspaceHint:
      'Select a parent item to include every variant, or select specific variants.',
    namePlaceholder: 'Example: Flash Discount',
    automaticCodeHint: 'OPTIONAL WHEN AUTOMATIC',
    name: 'Name',
    mode: 'Application mode',
    automatic: 'Automatic',
    code: 'Promo code',
    codeLabel: 'Code',
    scope: 'Scope',
    item: 'Item',
    variants: 'Specific variants',
    variantHint:
      'A parent item target applies to all variants. Select specific variants to limit the promotion.',
    category: 'Category',
    transaction: 'Transaction',
    discountType: 'Discount type',
    percentage: 'Percentage',
    fixed: 'Fixed amount',
    value: 'Discount value',
    currency: 'Currency',
    currencyHint: 'Required for fixed discounts, maximum discounts, or minimum purchases.',
    maximum: 'Maximum discount',
    minimum: 'Minimum purchase',
    effectiveFrom: 'Effective from',
    effectiveUntil: 'Effective until',
    effectivity: 'Period',
    locations: 'Locations',
    targets: 'Targets',
    allLocations: 'All locations',
    categoryItemScope: 'Items in category',
    allCategoryItems: 'All items in the category',
    selectedCategoryItems: 'Selected items only',
    selectCategoryItems: 'Choose items that receive the promotion',
    noCategoryItems: 'No active items are available in the selected categories.',
    enabled: 'Enabled',
    status: 'Status',
    active: 'Active',
    scheduled: 'Scheduled',
    expired: 'Expired',
    disabled: 'Disabled',
    noEnd: 'No end',
    immediate: 'Immediately',
    save: 'Save',
    cancel: 'Cancel',
    empty: 'No discounts or promotions yet.',
    saved: 'Promotion saved.',
    saveFailed: 'Promotion could not be saved.',
    invalid: 'Check the promotion details.',
    selectTarget: 'Select at least one target.',
    optional: 'Optional',
    percentageHint: 'Enter a percentage, for example 10 for 10%.',
    fixedHint: 'Enter a fixed amount in the selected currency.',
    selected: 'selected',
    all: 'All',
    noOptions: 'No active options are available.',
    targetSummary: 'Target',
    discount: 'Discount',
    forbidden: 'You do not have permission to change promotions.',
    serverError: 'The promotion service is unavailable. Try again.',
  },
} as const;

export type PromotionMessageKey = keyof (typeof messages)['id'];

export function usePromotionsLocalization() {
  const { locale } = useBackofficeLocalization();
  return (key: PromotionMessageKey) => messages[locale][key];
}
