import { useBackofficeLocalization } from '../../app/localization/backoffice-localization';

const messages = {
  id: {
    title: 'Diskon & promo',
    description:
      'Atur promo otomatis dan kode promo yang diterapkan pada transaksi yang memenuhi syarat.',
    add: 'Tambah promo',
    edit: 'Ubah promo',
    name: 'Nama',
    mode: 'Cara penerapan',
    automatic: 'Otomatis',
    code: 'Kode promo',
    codeLabel: 'Kode',
    scope: 'Cakupan',
    item: 'Item',
    category: 'Kategori',
    transaction: 'Transaksi',
    discountType: 'Jenis diskon',
    percentage: 'Persentase',
    fixed: 'Nominal',
    value: 'Nilai diskon',
    currency: 'Mata uang',
    currencyHint: 'Wajib untuk diskon nominal, maksimum diskon, atau minimum pembelian.',
    maximum: 'Maksimum diskon',
    minimum: 'Minimum pembelian',
    effectiveFrom: 'Mulai berlaku',
    effectiveUntil: 'Berakhir',
    effectivity: 'Periode',
    locations: 'Lokasi',
    targets: 'Target',
    allLocations: 'Semua lokasi',
    categoryItemScope: 'Item dalam kategori',
    allCategoryItems: 'Semua item dalam kategori',
    selectedCategoryItems: 'Item tertentu saja',
    selectCategoryItems: 'Pilih item yang mendapat promo',
    noCategoryItems: 'Tidak ada item aktif pada kategori yang dipilih.',
    enabled: 'Aktif',
    status: 'Status',
    active: 'Aktif',
    scheduled: 'Terjadwal',
    expired: 'Berakhir',
    disabled: 'Nonaktif',
    noEnd: 'Tanpa batas akhir',
    immediate: 'Langsung',
    save: 'Simpan',
    cancel: 'Batal',
    empty: 'Belum ada diskon atau promo.',
    saved: 'Promo disimpan.',
    saveFailed: 'Promo tidak dapat disimpan.',
    invalid: 'Periksa kembali data promo.',
    selectTarget: 'Pilih minimal satu target.',
    optional: 'Opsional',
    percentageHint: 'Masukkan persentase, misalnya 10 untuk 10%.',
    fixedHint: 'Masukkan nominal sesuai mata uang yang dipilih.',
    selected: 'dipilih',
    all: 'Semua',
    noOptions: 'Tidak ada pilihan aktif.',
    targetSummary: 'Target',
    discount: 'Diskon',
    forbidden: 'Anda tidak memiliki izin untuk mengubah promo.',
    serverError: 'Layanan promo sedang bermasalah. Coba lagi.',
  },
  en: {
    title: 'Discounts & promotions',
    description: 'Manage automatic promotions and promo codes applied to eligible transactions.',
    add: 'Add promotion',
    edit: 'Edit promotion',
    name: 'Name',
    mode: 'Application mode',
    automatic: 'Automatic',
    code: 'Promo code',
    codeLabel: 'Code',
    scope: 'Scope',
    item: 'Item',
    category: 'Category',
    transaction: 'Transaction',
    discountType: 'Discount type',
    percentage: 'Percentage',
    fixed: 'Fixed amount',
    value: 'Discount value',
    currency: 'Currency',
    currencyHint: 'Required for fixed discounts, maximum discounts, or minimum purchases.',
    maximum: 'Maximum discount',
    minimum: 'Minimum purchase',
    effectiveFrom: 'Effective from',
    effectiveUntil: 'Effective until',
    effectivity: 'Period',
    locations: 'Locations',
    targets: 'Targets',
    allLocations: 'All locations',
    categoryItemScope: 'Items in category',
    allCategoryItems: 'All items in the category',
    selectedCategoryItems: 'Selected items only',
    selectCategoryItems: 'Choose items that receive the promotion',
    noCategoryItems: 'No active items are available in the selected categories.',
    enabled: 'Enabled',
    status: 'Status',
    active: 'Active',
    scheduled: 'Scheduled',
    expired: 'Expired',
    disabled: 'Disabled',
    noEnd: 'No end',
    immediate: 'Immediately',
    save: 'Save',
    cancel: 'Cancel',
    empty: 'No discounts or promotions yet.',
    saved: 'Promotion saved.',
    saveFailed: 'Promotion could not be saved.',
    invalid: 'Check the promotion details.',
    selectTarget: 'Select at least one target.',
    optional: 'Optional',
    percentageHint: 'Enter a percentage, for example 10 for 10%.',
    fixedHint: 'Enter a fixed amount in the selected currency.',
    selected: 'selected',
    all: 'All',
    noOptions: 'No active options are available.',
    targetSummary: 'Target',
    discount: 'Discount',
    forbidden: 'You do not have permission to change promotions.',
    serverError: 'The promotion service is unavailable. Try again.',
  },
} as const;

export type PromotionMessageKey = keyof (typeof messages)['id'];

export function usePromotionsLocalization() {
  const { locale } = useBackofficeLocalization();
  return (key: PromotionMessageKey) => messages[locale][key];
}
