import { createContext, useCallback, useContext, useMemo, useState, type ReactNode } from 'react';

export type BackofficeLocale = 'id' | 'en';

const storageKey = 'digvation.pos.backoffice.locale.v1';

const messages = {
  id: {
    dashboard: 'Dasbor', masterData: 'Data Master', catalog: 'Katalog', employees: 'Karyawan',
    finance: 'Keuangan', financialAccounts: 'Akun Keuangan', expenses: 'Pengeluaran', reconciliation: 'Rekonsiliasi', transactionHistory: 'Riwayat transaksi',
    reporting: 'Pelaporan', reports: 'Laporan', configuration: 'Konfigurasi', business: 'Bisnis', tax: 'Pajak',
    accessControl: 'Kontrol Akses', logout: 'Keluar', profile: 'Profil', changePassword: 'Ubah kata sandi',
    language: 'Bahasa', indonesian: 'Bahasa Indonesia', english: 'English', online: 'Online',
    authenticatedUser: 'Pengguna terautentikasi', openNavigation: 'Buka menu navigasi', notifications: 'Notifikasi',
    openAccountMenu: 'Buka menu akun', userAccount: 'Akun pengguna',
    signIn: 'Masuk', signInToBackoffice: 'Masuk ke Backoffice', usernameOrPhone: 'Nama pengguna atau nomor telepon',
    password: 'Kata sandi', signInFailed: 'Masuk gagal. Periksa kredensial ruang kerja Anda lalu coba lagi.',
    sessionExpired: 'Sesi Anda telah berakhir. Silakan masuk kembali.', signedOut: 'Anda telah keluar.',
    startupBlocked: 'Memulai aplikasi diblokir', startupFailed: 'Backoffice tidak dapat dimulai.', unknownStartupError: 'Kesalahan awal tidak diketahui',
    overview: 'Ringkasan', workspaceReady: 'Ruang kerja Backoffice Anda siap.',
    accessUnavailable: 'Akses tidak tersedia', accessUnavailableDescription: 'Peran Anda saat ini tidak memberikan akses ke area ini.', goToDashboard: 'Ke dasbor',
    notAvailableYet: 'Belum tersedia', notAvailableDescription: 'Area ini akan tersedia ketika kemampuan Backoffice terkait telah disediakan.',
    taxDescription: 'Pengaturan pajak akan tersedia di sini.', accountAndRuntime: 'Akun & runtime', version: 'Versi', build: 'Build',
  },
  en: {
    dashboard: 'Dashboard', masterData: 'Master Data', catalog: 'Catalog', employees: 'Employees',
    finance: 'Finance', financialAccounts: 'Financial Accounts', expenses: 'Expenses', reconciliation: 'Reconciliation', transactionHistory: 'Transaction history',
    reporting: 'Reporting', reports: 'Reports', configuration: 'Configuration', business: 'Business', tax: 'Tax',
    accessControl: 'Access Control', logout: 'Logout', profile: 'Profile', changePassword: 'Change Password',
    language: 'Language', indonesian: 'Bahasa Indonesia', english: 'English', online: 'Online',
    authenticatedUser: 'Authenticated user', openNavigation: 'Open navigation menu', notifications: 'Notifications',
    openAccountMenu: 'Open account menu', userAccount: 'User account',
    signIn: 'Sign in', signInToBackoffice: 'Sign in to Backoffice', usernameOrPhone: 'Username or phone',
    password: 'Password', signInFailed: 'Sign-in failed. Check your workspace credentials and try again.',
    sessionExpired: 'Your session has expired. Please sign in again.', signedOut: 'You have signed out.',
    startupBlocked: 'Startup blocked', startupFailed: 'Backoffice could not initialize.', unknownStartupError: 'Unknown startup error',
    overview: 'Overview', workspaceReady: 'Your Backoffice workspace is ready.',
    accessUnavailable: 'Access unavailable', accessUnavailableDescription: 'Your current role does not grant access to this area.', goToDashboard: 'Go to dashboard',
    notAvailableYet: 'Not available yet', notAvailableDescription: 'This area will be available when its dedicated Backoffice capability is delivered.',
    taxDescription: 'Tax settings will be available here.', accountAndRuntime: 'Account & runtime', version: 'Version', build: 'Build',
  },
} as const;

const copy: Record<string, { id: string; en: string }> = {
  'Reporting': { id: 'Pelaporan', en: 'Reporting' }, 'Reports': { id: 'Laporan', en: 'Reports' },
  'Operational reports are calculated from the same authoritative facts used by POS operations.': { id: 'Laporan operasional dihitung dari fakta otoritatif yang sama dengan operasi POS.', en: 'Operational reports are calculated from the same authoritative facts used by POS operations.' },
  'Report': { id: 'Laporan', en: 'Report' }, 'Report type': { id: 'Jenis laporan', en: 'Report type' },
  'Export Excel': { id: 'Ekspor Excel', en: 'Export Excel' }, 'Export PDF': { id: 'Ekspor PDF', en: 'Export PDF' },
  'No report data is available for this period.': { id: 'Tidak ada data laporan untuk periode ini.', en: 'No report data is available for this period.' },
  'Business Performance Summary': { id: 'Ringkasan Kinerja Bisnis', en: 'Business Performance Summary' }, 'Transaction Report': { id: 'Laporan Transaksi', en: 'Transaction Report' }, 'Catalog Performance': { id: 'Kinerja Katalog', en: 'Catalog Performance' }, 'Employee Performance': { id: 'Kinerja Karyawan', en: 'Employee Performance' }, 'Payment Report': { id: 'Laporan Pembayaran', en: 'Payment Report' }, 'Expense Report': { id: 'Laporan Pengeluaran', en: 'Expense Report' }, 'Cash Report': { id: 'Laporan Kas', en: 'Cash Report' }, 'Settlement Report': { id: 'Laporan Settlement', en: 'Settlement Report' }, 'Reconciliation Report': { id: 'Laporan Rekonsiliasi', en: 'Reconciliation Report' }, 'Tax Report': { id: 'Laporan Pajak', en: 'Tax Report' }, 'Selling Location Performance': { id: 'Kinerja Lokasi Penjualan', en: 'Selling Location Performance' },
  'Export': { id: 'Ekspor', en: 'Export' },
  'Filters': { id: 'Filter', en: 'Filters' }, 'Clear filters': { id: 'Hapus filter', en: 'Clear filters' }, 'Active filters': { id: 'Filter aktif', en: 'Active filters' },
  'Search transaction or invoice number': { id: 'Cari nomor transaksi atau faktur', en: 'Search transaction or invoice number' },
  'Catalog lifecycle': { id: 'Siklus hidup katalog', en: 'Catalog lifecycle' }, 'Item type': { id: 'Tipe item', en: 'Item type' },
  'Employee status': { id: 'Status karyawan', en: 'Employee status' },
  'Location': { id: 'Lokasi', en: 'Location' }, 'All locations': { id: 'Semua lokasi', en: 'All locations' },
  'Revenue activity': { id: 'Aktivitas pendapatan', en: 'Revenue activity' }, 'Transaction activity': { id: 'Aktivitas transaksi', en: 'Transaction activity' },
  'Catalog activity': { id: 'Aktivitas katalog', en: 'Catalog activity' }, 'Contribution activity': { id: 'Aktivitas kontribusi', en: 'Contribution activity' },
  'Payment activity': { id: 'Aktivitas pembayaran', en: 'Payment activity' }, 'Expense activity': { id: 'Aktivitas pengeluaran', en: 'Expense activity' },
  'Cash movement activity': { id: 'Aktivitas pergerakan kas', en: 'Cash movement activity' }, 'Settlement activity': { id: 'Aktivitas penyelesaian', en: 'Settlement activity' },
  'Reconciliation activity': { id: 'Aktivitas rekonsiliasi', en: 'Reconciliation activity' }, 'Tax activity': { id: 'Aktivitas pajak', en: 'Tax activity' },
  'Location revenue comparison': { id: 'Perbandingan pendapatan lokasi', en: 'Location revenue comparison' },
  'Payment mix': { id: 'Komposisi pembayaran', en: 'Payment mix' },
  'Catalog mix': { id: 'Komposisi katalog', en: 'Catalog mix' }, 'Contribution mix': { id: 'Komposisi kontribusi', en: 'Contribution mix' },
  'Payment method mix': { id: 'Komposisi metode pembayaran', en: 'Payment method mix' }, 'Expense status': { id: 'Status pengeluaran', en: 'Expense status' },
  'Cash movement mix': { id: 'Komposisi pergerakan kas', en: 'Cash movement mix' }, 'Settlement status': { id: 'Status penyelesaian', en: 'Settlement status' },
  'Reconciliation status': { id: 'Status rekonsiliasi', en: 'Reconciliation status' }, 'Tax contribution': { id: 'Kontribusi pajak', en: 'Tax contribution' },
  'Revenue share': { id: 'Porsi pendapatan', en: 'Revenue share' }, 'Location performance': { id: 'Kinerja lokasi', en: 'Location performance' },
  'Payment and fulfillment insight': { id: 'Ikhtisar pembayaran dan pemenuhan', en: 'Payment and fulfillment insight' }, 'Top catalog items': { id: 'Item katalog teratas', en: 'Top catalog items' },
  'Top contributors': { id: 'Kontributor teratas', en: 'Top contributors' }, 'Payment status insight': { id: 'Ikhtisar status pembayaran', en: 'Payment status insight' },
  'Expense origin insight': { id: 'Ikhtisar asal pengeluaran', en: 'Expense origin insight' }, 'Account and location insight': { id: 'Ikhtisar akun dan lokasi', en: 'Account and location insight' },
  'Destination account insight': { id: 'Ikhtisar akun tujuan', en: 'Destination account insight' }, 'Discrepancy insight': { id: 'Ikhtisar selisih', en: 'Discrepancy insight' },
  'Tax code contribution': { id: 'Kontribusi kode pajak', en: 'Tax code contribution' }, 'Location ranking': { id: 'Peringkat lokasi', en: 'Location ranking' },
  'Cash and expense overview': { id: 'Ringkasan kas dan pengeluaran', en: 'Cash and expense overview' }, 'Transaction overview': { id: 'Ringkasan transaksi', en: 'Transaction overview' },
  'Catalog overview': { id: 'Ringkasan katalog', en: 'Catalog overview' }, 'Contribution overview': { id: 'Ringkasan kontribusi', en: 'Contribution overview' },
  'Payment overview': { id: 'Ringkasan pembayaran', en: 'Payment overview' }, 'Expense overview': { id: 'Ringkasan pengeluaran', en: 'Expense overview' },
  'Cash overview': { id: 'Ringkasan kas', en: 'Cash overview' }, 'Settlement overview': { id: 'Ringkasan penyelesaian', en: 'Settlement overview' },
  'Reconciliation overview': { id: 'Ringkasan rekonsiliasi', en: 'Reconciliation overview' }, 'Tax overview': { id: 'Ringkasan pajak', en: 'Tax overview' },
  'Location overview': { id: 'Ringkasan lokasi', en: 'Location overview' }, 'Selected period': { id: 'Periode terpilih', en: 'Selected period' },
  'Based on the selected period': { id: 'Berdasarkan periode terpilih', en: 'Based on the selected period' }, 'Detailed records': { id: 'Data terperinci', en: 'Detailed records' },
  'No analytics data is available for this period.': { id: 'Belum ada aktivitas pada periode ini.', en: 'No analytics data is available for this period.' }, 'data points': { id: 'titik data', en: 'data points' },
  'All analytics, details, and exports use this date range.': { id: 'Semua analitik, data terperinci, dan ekspor menggunakan rentang tanggal ini.', en: 'All analytics, details, and exports use this date range.' },
  'Operational detail for the selected report and date range.': { id: 'Rincian operasional untuk laporan dan rentang tanggal terpilih.', en: 'Operational detail for the selected report and date range.' },
  'Final Revenue': { id: 'Pendapatan akhir', en: 'Final Revenue' }, 'Transaction Count': { id: 'Jumlah transaksi', en: 'Transaction Count' },
  'Average Transaction Value': { id: 'Rata-rata nilai transaksi', en: 'Average Transaction Value' }, 'Quantity Sold': { id: 'Jumlah terjual', en: 'Quantity Sold' },
  'Successful Payment Amount': { id: 'Jumlah pembayaran berhasil', en: 'Successful Payment Amount' }, 'Item Count': { id: 'Jumlah item aktif', en: 'Active Item Count' },
  'Average Selling Value': { id: 'Rata-rata nilai penjualan', en: 'Average Selling Value' }, 'Contribution Revenue': { id: 'Pendapatan kontribusi', en: 'Contribution Revenue' },
  'Employee Count': { id: 'Jumlah karyawan berkontribusi', en: 'Contributing Employee Count' }, 'Contributed Transactions': { id: 'Transaksi berkontribusi', en: 'Contributed Transactions' },
  'Average Contribution': { id: 'Rata-rata kontribusi', en: 'Average Contribution' }, 'Successful Amount': { id: 'Jumlah berhasil', en: 'Successful Amount' },
  'Attempt Count': { id: 'Jumlah percobaan', en: 'Attempt Count' }, 'Successful Payments': { id: 'Pembayaran berhasil', en: 'Successful Payments' },
  'Failed Payments': { id: 'Pembayaran gagal', en: 'Failed Payments' }, 'Approved Expense Total': { id: 'Total pengeluaran disetujui', en: 'Approved Expense Total' },
  'Expense Count': { id: 'Jumlah pengeluaran', en: 'Expense Count' }, 'Pending Count': { id: 'Menunggu', en: 'Pending' }, 'Rejected Count': { id: 'Ditolak', en: 'Rejected' },
  'Cash In': { id: 'Kas masuk', en: 'Cash In' }, 'Cash Out': { id: 'Kas keluar', en: 'Cash Out' }, 'Net Movement': { id: 'Pergerakan bersih', en: 'Net Movement' },
  'Movement Count': { id: 'Jumlah pergerakan', en: 'Movement Count' }, 'Settled Amount': { id: 'Jumlah diselesaikan', en: 'Settled Amount' },
  'Settlement Count': { id: 'Jumlah penyelesaian', en: 'Settlement Count' }, 'Completed Count': { id: 'Selesai', en: 'Completed' }, 'Draft Count': { id: 'Draf', en: 'Draft' },
  'Reconciliation Count': { id: 'Jumlah rekonsiliasi', en: 'Reconciliation Count' }, 'Matched Count': { id: 'Cocok', en: 'Matched' },
  'Discrepancy Count': { id: 'Selisih', en: 'Discrepancy' }, 'Difference Amount': { id: 'Jumlah selisih', en: 'Difference Amount' },
  'Tax Amount': { id: 'Jumlah pajak', en: 'Tax Amount' }, 'Taxable Base': { id: 'Dasar kena pajak', en: 'Taxable Base' },
  'Included Tax': { id: 'Pajak termasuk', en: 'Included Tax' }, 'Excluded Tax': { id: 'Pajak tidak termasuk', en: 'Excluded Tax' },
  'Sale Number': { id: 'Nomor transaksi', en: 'Sale Number' }, 'Invoice Number': { id: 'Nomor faktur', en: 'Invoice Number' },
  'Occurred At': { id: 'Waktu kejadian', en: 'Occurred At' }, 'Selling Location': { id: 'Lokasi penjualan', en: 'Selling Location' },
  'Gross': { id: 'Bruto', en: 'Gross' }, 'Discount': { id: 'Diskon', en: 'Discount' }, 'Tax': { id: 'Pajak', en: 'Tax' },
  'Payment Attempts': { id: 'Percobaan pembayaran', en: 'Payment Attempts' }, 'Payment Statuses': { id: 'Status pembayaran', en: 'Payment Statuses' },
  'Fulfillment Statuses': { id: 'Status pemenuhan', en: 'Fulfillment Statuses' }, 'Rank': { id: 'Peringkat', en: 'Rank' },
  'Item Code': { id: 'Kode item', en: 'Item Code' }, 'Item Name': { id: 'Nama item', en: 'Item Name' },
  'Gross Revenue': { id: 'Pendapatan bruto', en: 'Gross Revenue' }, 'Discount Amount': { id: 'Jumlah diskon', en: 'Discount Amount' },
  'Selling Location Count': { id: 'Jumlah lokasi penjualan', en: 'Selling Location Count' }, 'Employee Code': { id: 'Kode karyawan', en: 'Employee Code' },
  'Employee Name': { id: 'Nama karyawan', en: 'Employee Name' }, 'Contributed Line Items': { id: 'Item yang dikontribusikan', en: 'Contributed Line Items' },
  'Average Contribution Per Transaction': { id: 'Rata-rata kontribusi per transaksi', en: 'Average Contribution Per Transaction' },
  'Top Catalog Item': { id: 'Item katalog teratas', en: 'Top Catalog Item' }, 'Method': { id: 'Metode', en: 'Method' },
  'Applied Amount': { id: 'Jumlah diterapkan', en: 'Applied Amount' }, 'Tendered Amount': { id: 'Jumlah diterima', en: 'Tendered Amount' },
  'Change Amount': { id: 'Jumlah kembalian', en: 'Change Amount' }, 'Provider Reference': { id: 'Referensi penyedia', en: 'Provider Reference' },
  'Financial Account': { id: 'Akun keuangan', en: 'Financial Account' }, 'Origin': { id: 'Asal', en: 'Origin' },
  'Approved At': { id: 'Waktu persetujuan', en: 'Approved At' }, 'Rejected At': { id: 'Waktu penolakan', en: 'Rejected At' },
  'Expense Linked': { id: 'Terkait pengeluaran', en: 'Expense Linked' }, 'Settlement Id': { id: 'Identitas penyelesaian', en: 'Settlement ID' },
  'Payment Method': { id: 'Metode pembayaran', en: 'Payment Method' }, 'Expected Amount': { id: 'Jumlah yang diharapkan', en: 'Expected Amount' },
  'Included Payment Count': { id: 'Jumlah pembayaran tercakup', en: 'Included Payment Count' }, 'Created At': { id: 'Waktu dibuat', en: 'Created At' },
  'Completed At': { id: 'Waktu selesai', en: 'Completed At' }, 'Actual Amount': { id: 'Jumlah aktual', en: 'Actual Amount' },
  'Tax Code': { id: 'Kode pajak', en: 'Tax Code' }, 'Tax Rate': { id: 'Tarif pajak', en: 'Tax Rate' }, 'Tax Treatment': { id: 'Perlakuan pajak', en: 'Tax Treatment' },
  'Location Code': { id: 'Kode lokasi', en: 'Location Code' }, 'Location Name': { id: 'Nama lokasi', en: 'Location Name' },
  'BACKOFFICE': { id: 'Backoffice', en: 'Backoffice' }, 'CASHIER': { id: 'Kasir', en: 'Cashier' },
  'PRODUCT': { id: 'Produk', en: 'Product' }, 'SERVICE': { id: 'Layanan', en: 'Service' },
  'CASH_IN': { id: 'Kas masuk', en: 'Cash in' }, 'CASH_OUT': { id: 'Kas keluar', en: 'Cash out' },
  'MATCHED': { id: 'Cocok', en: 'Matched' }, 'DISCREPANCY': { id: 'Selisih', en: 'Discrepancy' }, 'RESOLVED': { id: 'Diselesaikan', en: 'Resolved' },
  'DRAFT': { id: 'Draf', en: 'Draft' },
  'Business profile': { id: 'Profil bisnis', en: 'Business profile' },
  'Configuration': { id: 'Konfigurasi', en: 'Configuration' },
  'Selling locations': { id: 'Lokasi penjualan', en: 'Selling locations' },
  'Edit profile': { id: 'Ubah profil', en: 'Edit profile' },
  'Not configured': { id: 'Belum dikonfigurasi', en: 'Not configured' },
  'Add location': { id: 'Tambah lokasi', en: 'Add location' },
  'No selling locations have been created yet.': { id: 'Belum ada lokasi penjualan yang dibuat.', en: 'No selling locations have been created yet.' },
  'Active': { id: 'Aktif', en: 'Active' }, 'Inactive': { id: 'Nonaktif', en: 'Inactive' },
  'Cancel': { id: 'Batal', en: 'Cancel' }, 'Save': { id: 'Simpan', en: 'Save' },
  'Previous': { id: 'Sebelumnya', en: 'Previous' }, 'Next': { id: 'Berikutnya', en: 'Next' },
  'Add selling location': { id: 'Tambah lokasi penjualan', en: 'Add selling location' },
  'Save location': { id: 'Simpan lokasi', en: 'Save location' },
  'Location code': { id: 'Kode lokasi', en: 'Location code' }, 'Location name': { id: 'Nama lokasi', en: 'Location name' },
  'Deactivate selling location?': { id: 'Nonaktifkan lokasi penjualan?', en: 'Deactivate selling location?' },
  'Deactivate': { id: 'Nonaktifkan', en: 'Deactivate' },
  'Access Control': { id: 'Kontrol Akses', en: 'Access Control' }, 'Create role': { id: 'Tambah peran', en: 'Create role' },
  'Roles': { id: 'Peran', en: 'Roles' }, 'Users': { id: 'Pengguna', en: 'Users' },
  'Role': { id: 'Peran', en: 'Role' }, 'Permissions': { id: 'Izin', en: 'Permissions' },
  'Status': { id: 'Status', en: 'Status' }, 'Code': { id: 'Kode', en: 'Code' }, 'Name': { id: 'Nama', en: 'Name' },
  'Manage role': { id: 'Kelola peran', en: 'Manage role' }, 'Manage roles': { id: 'Kelola peran', en: 'Manage roles' },
  'Deactivate role': { id: 'Nonaktifkan peran', en: 'Deactivate role' }, 'Deactivate role?': { id: 'Nonaktifkan peran?', en: 'Deactivate role?' },
  'Role code': { id: 'Kode peran', en: 'Role code' }, 'Role name': { id: 'Nama peran', en: 'Role name' },
  'Save role': { id: 'Simpan peran', en: 'Save role' }, 'Manage user roles': { id: 'Kelola peran pengguna', en: 'Manage user roles' },
  'Save assignments': { id: 'Simpan penetapan', en: 'Save assignments' }, 'Protected': { id: 'Dilindungi', en: 'Protected' },
  'Catalog': { id: 'Katalog', en: 'Catalog' }, 'Items': { id: 'Item', en: 'Items' }, 'Categories': { id: 'Kategori', en: 'Categories' },
  'Item': { id: 'Item', en: 'Item' }, 'Type': { id: 'Tipe', en: 'Type' }, 'Category': { id: 'Kategori', en: 'Category' },
  'Default Price': { id: 'Harga default', en: 'Default Price' }, 'Variants': { id: 'Varian', en: 'Variants' },
  'Set your business identity and manage the selling locations available to this workspace.': { id: 'Atur identitas bisnis dan kelola lokasi penjualan yang tersedia untuk ruang kerja ini.', en: 'Set your business identity and manage the selling locations available to this workspace.' },
  'The business name used by your POS records.': { id: 'Nama bisnis yang digunakan oleh catatan POS Anda.', en: 'The business name used by your POS records.' },
  'Selling locations are the branches used by POS transactions and location-specific pricing.': { id: 'Lokasi penjualan adalah cabang yang digunakan oleh transaksi POS dan harga khusus lokasi.', en: 'Selling locations are the branches used by POS transactions and location-specific pricing.' },
  'Edit selling location': { id: 'Ubah lokasi penjualan', en: 'Edit selling location' },
  'This location will remain in historical records but cannot be used as an active selling location.': { id: 'Lokasi ini tetap ada dalam catatan historis, tetapi tidak dapat digunakan sebagai lokasi penjualan aktif.', en: 'This location will remain in historical records but cannot be used as an active selling location.' },
  'Set the name that identifies this business in POS records.': { id: 'Atur nama yang mengidentifikasi bisnis ini dalam catatan POS.', en: 'Set the name that identifies this business in POS records.' },
  'Save profile': { id: 'Simpan profil', en: 'Save profile' }, 'Business name': { id: 'Nama bisnis', en: 'Business name' },
  'A selling location is the branch context for POS sales and location-specific prices.': { id: 'Lokasi penjualan adalah konteks cabang untuk penjualan POS dan harga khusus lokasi.', en: 'A selling location is the branch context for POS sales and location-specific prices.' },
  'Location codes are permanent once created.': { id: 'Kode lokasi bersifat permanen setelah dibuat.', en: 'Location codes are permanent once created.' },
  'Showing': { id: 'Menampilkan', en: 'Showing' },
  'Manage items and categories.': { id: 'Kelola item dan kategori.', en: 'Manage items and categories.' },
  'Search item name or code...': { id: 'Cari nama atau kode item...', en: 'Search item name or code...' },
  'Search category name or code...': { id: 'Cari nama atau kode kategori...', en: 'Search category name or code...' },
  'Add item': { id: 'Tambah item', en: 'Add item' }, 'Add category': { id: 'Tambah kategori', en: 'Add category' },
  'View details': { id: 'Lihat detail', en: 'View details' }, 'Edit item': { id: 'Ubah item', en: 'Edit item' }, 'Edit category': { id: 'Ubah kategori', en: 'Edit category' },
  'No matching items found.': { id: 'Tidak ada item yang sesuai.', en: 'No matching items found.' }, 'No catalog items are available.': { id: 'Belum ada item katalog.', en: 'No catalog items are available.' },
  'No matching categories found.': { id: 'Tidak ada kategori yang sesuai.', en: 'No matching categories found.' }, 'No catalog categories are available.': { id: 'Belum ada kategori katalog.', en: 'No catalog categories are available.' },
  'Close': { id: 'Tutup', en: 'Close' }, 'Price': { id: 'Harga', en: 'Price' }, 'Manage variant price': { id: 'Kelola harga varian', en: 'Manage variant price' },
  'Add': { id: 'Tambah', en: 'Add' }, 'Edit': { id: 'Ubah', en: 'Edit' }, 'Variant': { id: 'Varian', en: 'Variant' },
  'Product': { id: 'Produk', en: 'Product' }, 'Service': { id: 'Layanan', en: 'Service' }, 'Draft': { id: 'Draf', en: 'Draft' }, 'Cancelled': { id: 'Dibatalkan', en: 'Cancelled' },
  'Manage tenant roles and user role assignments. Permissions are defined by the POS platform.': { id: 'Kelola peran tenant dan penetapan peran pengguna. Izin ditentukan oleh platform POS.', en: 'Manage tenant roles and user role assignments. Permissions are defined by the POS platform.' },
  'Users will no longer receive this role\'s permissions.': { id: 'Pengguna tidak lagi menerima izin dari peran ini.', en: 'Users will no longer receive this role\'s permissions.' },
  'System role': { id: 'Peran sistem', en: 'System role' }, 'No roles are available for this workspace.': { id: 'Tidak ada peran untuk ruang kerja ini.', en: 'No roles are available for this workspace.' },
  'User': { id: 'Pengguna', en: 'User' }, 'Username': { id: 'Nama pengguna', en: 'Username' }, 'No username': { id: 'Tidak ada nama pengguna', en: 'No username' },
  'No roles assigned': { id: 'Belum ada peran', en: 'No roles assigned' }, 'No POS users are available for this workspace.': { id: 'Tidak ada pengguna POS untuk ruang kerja ini.', en: 'No POS users are available for this workspace.' },
  'System roles are protected by the POS authorization policy.': { id: 'Peran sistem dilindungi oleh kebijakan otorisasi POS.', en: 'System roles are protected by the POS authorization policy.' },
  'Role permissions are assigned from the platform permission registry.': { id: 'Izin peran ditetapkan dari registri izin platform.', en: 'Role permissions are assigned from the platform permission registry.' },
  'Not assigned': { id: 'Belum ditetapkan', en: 'Not assigned' }, 'Description': { id: 'Deskripsi', en: 'Description' }, 'No description': { id: 'Tidak ada deskripsi', en: 'No description' },
  'Fulfillment': { id: 'Pemenuhan', en: 'Fulfillment' }, 'Service configuration': { id: 'Konfigurasi layanan', en: 'Service configuration' },
  'Default duration': { id: 'Durasi default', en: 'Default duration' },
  'Employee assignment': { id: 'Penugasan karyawan', en: 'Employee assignment' }, 'Employee contribution': { id: 'Kontribusi karyawan', en: 'Employee contribution' },
  'Allowed': { id: 'Diizinkan', en: 'Allowed' }, 'Not allowed': { id: 'Tidak diizinkan', en: 'Not allowed' },
  'Price history': { id: 'Riwayat harga', en: 'Price history' }, 'Set price': { id: 'Atur harga', en: 'Set price' }, 'Change price': { id: 'Ubah harga', en: 'Change price' },
  'Manage variants for this item.': { id: 'Kelola varian untuk item ini.', en: 'Manage variants for this item.' }, 'Add variant': { id: 'Tambah varian', en: 'Add variant' },
  'No variants.': { id: 'Belum ada varian.', en: 'No variants.' }, 'Edit variant': { id: 'Ubah varian', en: 'Edit variant' },
  'Loading...': { id: 'Memuat...', en: 'Loading...' }, 'Not set': { id: 'Belum diatur', en: 'Not set' }, 'Uses default price': { id: 'Menggunakan harga default', en: 'Uses default price' },
  'Effective from': { id: 'Berlaku mulai', en: 'Effective from' }, 'Effective until': { id: 'Berlaku sampai', en: 'Effective until' }, 'Cancel price': { id: 'Batalkan harga', en: 'Cancel price' },
  'Basic information': { id: 'Informasi dasar', en: 'Basic information' }, 'No default price history.': { id: 'Belum ada riwayat harga default.', en: 'No default price history.' },
  'Cancel price?': { id: 'Batalkan harga?', en: 'Cancel price?' }, 'Price history is retained, but this price no longer applies.': { id: 'Riwayat harga tetap tersimpan, tetapi harga ini tidak lagi berlaku.', en: 'Price history is retained, but this price no longer applies.' },
  'Variant price': { id: 'Harga varian', en: 'Variant price' }, 'Change default price': { id: 'Ubah harga default', en: 'Change default price' }, 'Save price': { id: 'Simpan harga', en: 'Save price' }, 'New price': { id: 'Harga baru', en: 'New price' },
  'Price updated.': { id: 'Harga berhasil diperbarui.', en: 'Price updated.' }, 'Price cancelled.': { id: 'Harga berhasil dibatalkan.', en: 'Price cancelled.' },
  'Could not update price.': { id: 'Gagal memperbarui harga.', en: 'Could not update price.' }, 'Could not cancel price.': { id: 'Gagal membatalkan harga.', en: 'Could not cancel price.' },
  'Currency:': { id: 'Mata uang:', en: 'Currency:' }, 'No variant-specific price history.': { id: 'Belum ada harga khusus untuk varian ini.', en: 'No variant-specific price history.' },
  'Effective now': { id: 'Berlaku sekarang', en: 'Effective now' }, 'Variant prices are final prices, not differences from the default price.': { id: 'Harga varian adalah harga final, bukan selisih dari harga default.', en: 'Variant prices are final prices, not differences from the default price.' },
  'Item added.': { id: 'Item berhasil ditambahkan.', en: 'Item added.' }, 'Item updated.': { id: 'Item berhasil diperbarui.', en: 'Item updated.' }, 'Could not save item.': { id: 'Gagal menyimpan item.', en: 'Could not save item.' },
  'Item code': { id: 'Kode item', en: 'Item code' }, 'Item name': { id: 'Nama item', en: 'Item name' }, 'Optional, in minutes.': { id: 'Opsional, dalam menit.', en: 'Optional, in minutes.' }, 'Allow employee contribution': { id: 'Izinkan kontribusi karyawan', en: 'Allow employee contribution' },
  'Leave blank to generate a code automatically.': { id: 'Kosongkan untuk membuat kode otomatis.', en: 'Leave blank to generate a code automatically.' }, 'Code cannot be changed after creation.': { id: 'Kode tidak dapat diubah setelah dibuat.', en: 'Code cannot be changed after creation.' },
  'Item code and type cannot be changed after creation.': { id: 'Kode dan tipe item tidak dapat diubah setelah dibuat.', en: 'Item code and type cannot be changed after creation.' }, 'Item code and type cannot be changed.': { id: 'Kode dan tipe item tidak dapat diubah.', en: 'Item code and type cannot be changed.' },
  'Instant': { id: 'Instan', en: 'Instant' }, 'Tracked': { id: 'Terlacak', en: 'Tracked' }, 'None': { id: 'Tidak ada', en: 'None' }, 'Optional': { id: 'Opsional', en: 'Optional' }, 'Required': { id: 'Wajib', en: 'Required' }, 'Default duration must be a positive whole number.': { id: 'Durasi default harus berupa bilangan bulat positif.', en: 'Default duration must be a positive whole number.' },
  'Category added.': { id: 'Kategori berhasil ditambahkan.', en: 'Category added.' }, 'Category updated.': { id: 'Kategori berhasil diperbarui.', en: 'Category updated.' }, 'Could not save category.': { id: 'Gagal menyimpan kategori.', en: 'Could not save category.' },
  'Operations': { id: 'Operasional', en: 'Operations' }, 'Backoffice foundation': { id: 'Fondasi Backoffice', en: 'Backoffice foundation' }, 'Branches': { id: 'Cabang', en: 'Branches' }, 'Pricing & Tax': { id: 'Harga & Pajak', en: 'Pricing & Tax' },
  'No fake dashboard metrics are shown. Management capabilities appear only when their backend contract and frontend checkpoint are approved.': { id: 'Tidak ada metrik dasbor palsu yang ditampilkan. Kemampuan pengelolaan hanya muncul setelah kontrak backend dan checkpoint frontend disetujui.', en: 'No fake dashboard metrics are shown. Management capabilities appear only when their backend contract and frontend checkpoint are approved.' },
  'Business profile updated.': { id: 'Profil bisnis berhasil diperbarui.', en: 'Business profile updated.' }, 'Could not update business profile.': { id: 'Gagal memperbarui profil bisnis.', en: 'Could not update business profile.' },
  'Selling location added.': { id: 'Lokasi penjualan berhasil ditambahkan.', en: 'Selling location added.' }, 'Selling location updated.': { id: 'Lokasi penjualan berhasil diperbarui.', en: 'Selling location updated.' }, 'Selling location deactivated.': { id: 'Lokasi penjualan berhasil dinonaktifkan.', en: 'Selling location deactivated.' }, 'Could not save selling location.': { id: 'Gagal menyimpan lokasi penjualan.', en: 'Could not save selling location.' },
  'Role added.': { id: 'Peran berhasil ditambahkan.', en: 'Role added.' }, 'Role updated.': { id: 'Perubahan peran berhasil disimpan.', en: 'Role updated.' }, 'Role deactivated.': { id: 'Peran berhasil dinonaktifkan.', en: 'Role deactivated.' }, 'Could not save role.': { id: 'Gagal menyimpan peran.', en: 'Could not save role.' }, 'Could not deactivate role.': { id: 'Gagal menonaktifkan peran.', en: 'Could not deactivate role.' }, 'User roles updated.': { id: 'Peran pengguna berhasil diperbarui.', en: 'User roles updated.' }, 'Could not update user roles.': { id: 'Gagal memperbarui peran pengguna.', en: 'Could not update user roles.' },
  'A new price is added to effective history; the previous price is unchanged.': { id: 'Harga baru ditambahkan ke riwayat efektif; harga sebelumnya tidak diubah.', en: 'A new price is added to effective history; the previous price is unchanged.' },
  'Only variant-specific prices are recorded here. The item default price is not variant history.': { id: 'Hanya harga khusus varian yang dicatat di sini. Harga default item bukan riwayat varian.', en: 'Only variant-specific prices are recorded here. The item default price is not variant history.' },
  'Enter your username or phone number': { id: 'Masukkan nama pengguna atau nomor telepon', en: 'Enter your username or phone number' },
  'Enter your password': { id: 'Masukkan kata sandi Anda', en: 'Enter your password' },
  'Master Data': { id: 'Data Master', en: 'Master Data' }, 'Employees': { id: 'Karyawan', en: 'Employees' }, 'Manage employees available to POS operations.': { id: 'Kelola karyawan yang tersedia untuk operasional POS.', en: 'Manage employees available to POS operations.' },
  'Display name': { id: 'Nama tampilan', en: 'Display name' }, 'Updated': { id: 'Diperbarui', en: 'Updated' }, 'Created': { id: 'Dibuat', en: 'Created' }, 'All': { id: 'Semua', en: 'All' },
  'Search employee code or name...': { id: 'Cari kode atau nama karyawan...', en: 'Search employee code or name...' }, 'Add employee': { id: 'Tambah karyawan', en: 'Add employee' }, 'Edit employee': { id: 'Ubah karyawan', en: 'Edit employee' }, 'Employee code': { id: 'Kode karyawan', en: 'Employee code' }, 'Employee details': { id: 'Detail karyawan', en: 'Employee details' },
  'No matching employees found.': { id: 'Tidak ada karyawan yang sesuai.', en: 'No matching employees found.' }, 'No employees are available.': { id: 'Belum ada karyawan.', en: 'No employees are available.' }, 'Deactivate employee': { id: 'Nonaktifkan karyawan', en: 'Deactivate employee' }, 'Activate employee': { id: 'Aktifkan karyawan', en: 'Activate employee' },
  'Deactivate employee?': { id: 'Nonaktifkan karyawan?', en: 'Deactivate employee?' }, 'Activate employee?': { id: 'Aktifkan karyawan?', en: 'Activate employee?' },
  'This employee remains in historical records but cannot be selected for new POS assignments.': { id: 'Karyawan ini tetap ada dalam catatan historis, tetapi tidak dapat dipilih untuk penugasan POS baru.', en: 'This employee remains in historical records but cannot be selected for new POS assignments.' }, 'This employee can be selected for POS assignments again.': { id: 'Karyawan ini dapat dipilih untuk penugasan POS kembali.', en: 'This employee can be selected for POS assignments again.' },
  'Employees are created Active.': { id: 'Karyawan baru dibuat Aktif.', en: 'Employees are created Active.' }, 'Employee code cannot be changed after creation.': { id: 'Kode karyawan tidak dapat diubah setelah dibuat.', en: 'Employee code cannot be changed after creation.' }, 'Employee added.': { id: 'Karyawan berhasil ditambahkan.', en: 'Employee added.' }, 'Employee updated.': { id: 'Karyawan berhasil diperbarui.', en: 'Employee updated.' },
  'Could not save employee.': { id: 'Gagal menyimpan karyawan.', en: 'Could not save employee.' }, 'Employee data changed. The latest data has been loaded; review it before trying again.': { id: 'Data karyawan telah berubah. Data terbaru telah dimuat; tinjau sebelum mencoba lagi.', en: 'Employee data changed. The latest data has been loaded; review it before trying again.' }, 'For example, Ari Pratama': { id: 'Contoh, Ari Pratama', en: 'For example, Ari Pratama' },
  'Join date': { id: 'Tanggal bergabung', en: 'Join date' }, 'Select join date': { id: 'Pilih tanggal bergabung', en: 'Select join date' },
  'Leave Employee Code blank to generate it automatically.': { id: 'Kosongkan Kode Karyawan untuk membuatnya secara otomatis.', en: 'Leave Employee Code blank to generate it automatically.' },
  'Employee Information': { id: 'Informasi karyawan', en: 'Employee Information' }, 'System Information': { id: 'Informasi sistem', en: 'System Information' },
  'Reactivate employee?': { id: 'Aktifkan kembali karyawan?', en: 'Reactivate employee?' }, 'Reactivate': { id: 'Aktifkan kembali', en: 'Reactivate' },
  'Reason': { id: 'Alasan', en: 'Reason' }, 'Reason is optional and will be recorded in employee history.': { id: 'Alasan bersifat opsional dan akan dicatat dalam riwayat karyawan.', en: 'Reason is optional and will be recorded in employee history.' },
  'Optional reason for this status change': { id: 'Alasan opsional untuk perubahan status ini', en: 'Optional reason for this status change' },
  'Employee deactivated.': { id: 'Karyawan berhasil dinonaktifkan.', en: 'Employee deactivated.' }, 'Employee reactivated.': { id: 'Karyawan berhasil diaktifkan kembali.', en: 'Employee reactivated.' },
  'Employee History': { id: 'Riwayat Karyawan', en: 'Employee History' }, 'Event': { id: 'Peristiwa', en: 'Event' }, 'Date / Time': { id: 'Tanggal / Waktu', en: 'Date / Time' },
  'Changed by': { id: 'Diubah oleh', en: 'Changed by' }, 'Joined': { id: 'Bergabung', en: 'Joined' }, 'Deactivated': { id: 'Dinonaktifkan', en: 'Deactivated' }, 'Reactivated': { id: 'Diaktifkan kembali', en: 'Reactivated' },
  'No employee history is available.': { id: 'Belum ada riwayat karyawan.', en: 'No employee history is available.' },
  'Could not load employee details.': { id: 'Detail karyawan tidak dapat dimuat.', en: 'Could not load employee details.' },
  'Tenure': { id: 'Masa kerja', en: 'Tenure' }, 'Current status': { id: 'Status saat ini', en: 'Current status' },
  'year': { id: 'tahun', en: 'year' }, 'years': { id: 'tahun', en: 'years' }, 'month': { id: 'bulan', en: 'month' }, 'months': { id: 'bulan', en: 'months' }, 'day': { id: 'hari', en: 'day' }, 'days': { id: 'hari', en: 'days' }, 'Machine': { id: 'Mesin', en: 'Machine' },
  'Financial Accounts': { id: 'Akun Keuangan', en: 'Financial Accounts' },
  'Configure settlement destinations and location-specific payment routing.': { id: 'Konfigurasikan tujuan penyelesaian dan perutean pembayaran khusus lokasi.', en: 'Configure settlement destinations and location-specific payment routing.' },
  'Accounts': { id: 'Akun', en: 'Accounts' }, 'Payment routing': { id: 'Perutean pembayaran', en: 'Payment routing' },
  'Account code': { id: 'Kode akun', en: 'Account code' }, 'Account name': { id: 'Nama akun', en: 'Account name' }, 'Account type': { id: 'Jenis akun', en: 'Account type' },
  'Currency': { id: 'Mata uang', en: 'Currency' }, 'Destination': { id: 'Tujuan', en: 'Destination' },
  'Cash account': { id: 'Akun kas', en: 'Cash account' }, 'Bank account': { id: 'Rekening bank', en: 'Bank account' }, 'E-wallet account': { id: 'Akun dompet digital', en: 'E-wallet account' }, 'On-site cash': { id: 'Kas di lokasi', en: 'On-site cash' },
  'Search account code or name...': { id: 'Cari kode atau nama akun...', en: 'Search account code or name...' },
  'Add account': { id: 'Tambah akun', en: 'Add account' }, 'Edit account': { id: 'Ubah akun', en: 'Edit account' },
  'Deactivate account': { id: 'Nonaktifkan akun', en: 'Deactivate account' }, 'Activate account': { id: 'Aktifkan akun', en: 'Activate account' },
  'No matching financial accounts found.': { id: 'Tidak ada akun keuangan yang sesuai.', en: 'No matching financial accounts found.' },
  'No financial accounts are configured.': { id: 'Belum ada akun keuangan yang dikonfigurasi.', en: 'No financial accounts are configured.' },
  'Could not load financial accounts.': { id: 'Akun keuangan tidak dapat dimuat.', en: 'Could not load financial accounts.' },
  'Try loading the account list again.': { id: 'Coba muat kembali daftar akun.', en: 'Try loading the account list again.' },
  'Financial account added.': { id: 'Akun keuangan berhasil ditambahkan.', en: 'Financial account added.' },
  'Financial account updated.': { id: 'Akun keuangan berhasil diperbarui.', en: 'Financial account updated.' },
  'Financial account activated.': { id: 'Akun keuangan berhasil diaktifkan.', en: 'Financial account activated.' },
  'Financial account deactivated.': { id: 'Akun keuangan berhasil dinonaktifkan.', en: 'Financial account deactivated.' },
  'Could not save financial account.': { id: 'Akun keuangan tidak dapat disimpan.', en: 'Could not save financial account.' },
  'Could not update financial account.': { id: 'Akun keuangan tidak dapat diperbarui.', en: 'Could not update financial account.' },
  'Create a destination for collected payments.': { id: 'Buat tujuan untuk pembayaran yang diterima.', en: 'Create a destination for collected payments.' },
  'Account code, type, and currency cannot be changed.': { id: 'Kode, jenis, dan mata uang akun tidak dapat diubah.', en: 'Account code, type, and currency cannot be changed.' },
  'For example, Main settlement account': { id: 'Contoh, Akun penyelesaian utama', en: 'For example, Main settlement account' },
  'Bank / institution': { id: 'Bank / institusi', en: 'Bank / institution' }, 'Wallet provider': { id: 'Penyedia dompet digital', en: 'Wallet provider' },
  'Account number': { id: 'Nomor rekening', en: 'Account number' }, 'Wallet account': { id: 'Akun dompet digital', en: 'Wallet account' },
  'Account holder name': { id: 'Nama pemilik akun', en: 'Account holder name' }, 'Financial account details': { id: 'Detail akun keuangan', en: 'Financial account details' },
  'Payment method': { id: 'Metode pembayaran', en: 'Payment method' }, 'Settlement destination': { id: 'Tujuan penyelesaian', en: 'Settlement destination' },
  'Bank transfer': { id: 'Transfer bank', en: 'Bank transfer' }, 'Cash': { id: 'Tunai', en: 'Cash' }, 'E-wallet': { id: 'Dompet digital', en: 'E-wallet' },
  'No payment routes are configured.': { id: 'Belum ada rute pembayaran yang dikonfigurasi.', en: 'No payment routes are configured.' },
  'Could not load payment routing.': { id: 'Perutean pembayaran tidak dapat dimuat.', en: 'Could not load payment routing.' },
  'Try loading the routing list again.': { id: 'Coba muat kembali daftar perutean.', en: 'Try loading the routing list again.' },
  'Add route': { id: 'Tambah rute', en: 'Add route' }, 'Edit route': { id: 'Ubah rute', en: 'Edit route' },
  'Route collected payments to the configured settlement destination.': { id: 'Arahkan pembayaran yang diterima ke tujuan penyelesaian yang dikonfigurasi.', en: 'Route collected payments to the configured settlement destination.' },
  'Payment route added.': { id: 'Rute pembayaran berhasil ditambahkan.', en: 'Payment route added.' },
  'Payment route updated.': { id: 'Rute pembayaran berhasil diperbarui.', en: 'Payment route updated.' },
  'Could not save payment route.': { id: 'Rute pembayaran tidak dapat disimpan.', en: 'Could not save payment route.' },
  'Select an option': { id: 'Pilih opsi', en: 'Select an option' },
  'Cash, settlements & reconciliation': { id: 'Kas, penyelesaian & rekonsiliasi', en: 'Cash, settlements & reconciliation' },
  'Review cash position, settle accepted payments, and record reconciliation outcomes.': { id: 'Tinjau posisi kas, selesaikan pembayaran yang diterima, dan catat hasil rekonsiliasi.', en: 'Review cash position, settle accepted payments, and record reconciliation outcomes.' },
  'Cash position': { id: 'Posisi kas', en: 'Cash position' }, 'Settlements': { id: 'Penyelesaian', en: 'Settlements' }, 'Reconciliation': { id: 'Rekonsiliasi', en: 'Reconciliation' },
  'Accepted cash': { id: 'Kas diterima', en: 'Accepted cash' }, 'Cash movements': { id: 'Pergerakan kas', en: 'Cash movements' }, 'Record cash movement': { id: 'Catat pergerakan kas', en: 'Record cash movement' },
  'Could not load cash operations.': { id: 'Operasi kas tidak dapat dimuat.', en: 'Could not load cash operations.' }, 'Try loading cash operations again.': { id: 'Coba muat operasi kas lagi.', en: 'Try loading cash operations again.' }, 'No cash positions are available.': { id: 'Belum ada posisi kas.', en: 'No cash positions are available.' },
  'Movement type': { id: 'Jenis pergerakan', en: 'Movement type' }, 'Cash in': { id: 'Kas masuk', en: 'Cash in' }, 'Cash out': { id: 'Kas keluar', en: 'Cash out' }, 'Amount': { id: 'Jumlah', en: 'Amount' }, 'Note': { id: 'Catatan', en: 'Note' },
  'No cash movements are recorded.': { id: 'Belum ada pergerakan kas.', en: 'No cash movements are recorded.' }, 'Cash movement recorded.': { id: 'Pergerakan kas dicatat.', en: 'Cash movement recorded.' }, 'Could not record cash movement.': { id: 'Pergerakan kas tidak dapat dicatat.', en: 'Could not record cash movement.' },
  'Create settlement': { id: 'Buat penyelesaian', en: 'Create settlement' }, 'No settlements are available.': { id: 'Belum ada penyelesaian.', en: 'No settlements are available.' }, 'Could not load settlements.': { id: 'Penyelesaian tidak dapat dimuat.', en: 'Could not load settlements.' }, 'Try loading settlements again.': { id: 'Coba muat penyelesaian lagi.', en: 'Try loading settlements again.' },
  'Creates a draft from all unallocated successful payments for the selected routing destination.': { id: 'Membuat draf dari semua pembayaran berhasil yang belum dialokasikan untuk tujuan perutean terpilih.', en: 'Creates a draft from all unallocated successful payments for the selected routing destination.' }, 'Settlement created.': { id: 'Penyelesaian dibuat.', en: 'Settlement created.' }, 'Could not create settlement.': { id: 'Penyelesaian tidak dapat dibuat.', en: 'Could not create settlement.' }, 'Settlement details': { id: 'Detail penyelesaian', en: 'Settlement details' }, 'Expected amount': { id: 'Jumlah yang diharapkan', en: 'Expected amount' }, 'Payments': { id: 'Pembayaran', en: 'Payments' }, 'Complete settlement': { id: 'Selesaikan penyelesaian', en: 'Complete settlement' }, 'Settlement updated.': { id: 'Penyelesaian diperbarui.', en: 'Settlement updated.' }, 'Could not update settlement.': { id: 'Penyelesaian tidak dapat diperbarui.', en: 'Could not update settlement.' },
  'Record reconciliation': { id: 'Catat rekonsiliasi', en: 'Record reconciliation' }, 'No reconciliations are available.': { id: 'Belum ada rekonsiliasi.', en: 'No reconciliations are available.' }, 'Could not load reconciliation.': { id: 'Rekonsiliasi tidak dapat dimuat.', en: 'Could not load reconciliation.' }, 'Try loading reconciliation again.': { id: 'Coba muat rekonsiliasi lagi.', en: 'Try loading reconciliation again.' }, 'Settlement': { id: 'Penyelesaian', en: 'Settlement' }, 'Actual amount': { id: 'Jumlah aktual', en: 'Actual amount' }, 'Difference': { id: 'Selisih', en: 'Difference' }, 'Reconciliation recorded.': { id: 'Rekonsiliasi dicatat.', en: 'Reconciliation recorded.' }, 'Could not record reconciliation.': { id: 'Rekonsiliasi tidak dapat dicatat.', en: 'Could not record reconciliation.' },
  'Finance': { id: 'Keuangan', en: 'Finance' }, 'Date': { id: 'Tanggal', en: 'Date' }, 'Expenses': { id: 'Pengeluaran', en: 'Expenses' },
  'Record and review cash expenses by selling location and cash account.': { id: 'Catat dan tinjau pengeluaran kas berdasarkan lokasi penjualan dan akun kas.', en: 'Record and review cash expenses by selling location and cash account.' },
  'Search description, account, or location...': { id: 'Cari deskripsi, akun, atau lokasi...', en: 'Search description, account, or location...' },
  'No expenses are recorded.': { id: 'Belum ada pengeluaran yang dicatat.', en: 'No expenses are recorded.' },
  'View expense': { id: 'Lihat pengeluaran', en: 'View expense' }, 'Record expense': { id: 'Catat pengeluaran', en: 'Record expense' },
  'Expense recorded.': { id: 'Pengeluaran dicatat.', en: 'Expense recorded.' }, 'Could not record expense.': { id: 'Pengeluaran tidak dapat dicatat.', en: 'Could not record expense.' },
  'Expense details': { id: 'Detail pengeluaran', en: 'Expense details' },
  'Record, review, and approve cash expenses.': { id: 'Catat, tinjau, dan setujui pengeluaran kas.', en: 'Record, review, and approve cash expenses.' },
  'Pending': { id: 'Menunggu', en: 'Pending' }, 'Approved': { id: 'Disetujui', en: 'Approved' }, 'Rejected': { id: 'Ditolak', en: 'Rejected' },
  'Edit expense': { id: 'Ubah pengeluaran', en: 'Edit expense' }, 'Approve expense': { id: 'Setujui pengeluaran', en: 'Approve expense' }, 'Reject expense': { id: 'Tolak pengeluaran', en: 'Reject expense' },
  'Reject expense?': { id: 'Tolak pengeluaran?', en: 'Reject expense?' }, 'Reject': { id: 'Tolak', en: 'Reject' },
  'This expense will not post a cash movement.': { id: 'Pengeluaran ini tidak akan membukukan pergerakan kas.', en: 'This expense will not post a cash movement.' },
  'Expense updated.': { id: 'Pengeluaran diperbarui.', en: 'Expense updated.' }, 'Could not save expense.': { id: 'Pengeluaran tidak dapat disimpan.', en: 'Could not save expense.' },
  'Transaction history': { id: 'Riwayat transaksi', en: 'Transaction history' }, 'Review sale, payment, and fulfillment facts without changing their lifecycle.': { id: 'Tinjau fakta penjualan, pembayaran, dan pemenuhan tanpa mengubah siklus hidupnya.', en: 'Review sale, payment, and fulfillment facts without changing their lifecycle.' },
  transactionHistory: { id: 'Riwayat transaksi', en: 'Transaction history' },
  'Search payment reference or location...': { id: 'Cari referensi pembayaran atau lokasi...', en: 'Search payment reference or location...' }, 'No transactions match the current filters.': { id: 'Tidak ada transaksi yang sesuai dengan filter saat ini.', en: 'No transactions match the current filters.' },
  'Could not load transaction history.': { id: 'Riwayat transaksi tidak dapat dimuat.', en: 'Could not load transaction history.' }, 'Try loading transaction history again.': { id: 'Coba muat riwayat transaksi lagi.', en: 'Try loading transaction history again.' },
  'Sale': { id: 'Penjualan', en: 'Sale' }, 'Total': { id: 'Total', en: 'Total' }, 'Sale status': { id: 'Status penjualan', en: 'Sale status' }, 'Payment status': { id: 'Status pembayaran', en: 'Payment status' }, 'Fulfillment status': { id: 'Status pemenuhan', en: 'Fulfillment status' }, 'From': { id: 'Dari', en: 'From' }, 'To': { id: 'Sampai', en: 'To' },
  'Transaction number': { id: 'Nomor transaksi', en: 'Transaction number' }, 'Invoice number': { id: 'Nomor faktur', en: 'Invoice number' },
  'View transaction': { id: 'Lihat transaksi', en: 'View transaction' }, 'Transaction details': { id: 'Detail transaksi', en: 'Transaction details' }, 'Loading transaction details...': { id: 'Memuat detail transaksi...', en: 'Loading transaction details...' },
  'Could not load transaction details.': { id: 'Detail transaksi tidak dapat dimuat.', en: 'Could not load transaction details.' }, 'Close this dialog and try again.': { id: 'Tutup dialog ini lalu coba lagi.', en: 'Close this dialog and try again.' },
  'Sale information': { id: 'Informasi penjualan', en: 'Sale information' }, 'Payment information': { id: 'Informasi pembayaran', en: 'Payment information' }, 'Fulfillment information': { id: 'Informasi pemenuhan', en: 'Fulfillment information' },
  'No payment attempts are recorded.': { id: 'Belum ada percobaan pembayaran yang dicatat.', en: 'No payment attempts are recorded.' }, 'No tracked fulfillment is recorded.': { id: 'Belum ada pemenuhan terlacak yang dicatat.', en: 'No tracked fulfillment is recorded.' },
  'OPEN': { id: 'Terbuka', en: 'Open' }, 'FINALIZED': { id: 'Difinalisasi', en: 'Finalized' }, 'VOIDED': { id: 'Dibatalkan', en: 'Voided' }, 'SUCCEEDED': { id: 'Berhasil', en: 'Succeeded' }, 'FAILED': { id: 'Gagal', en: 'Failed' }, 'CANCELLED': { id: 'Dibatalkan', en: 'Cancelled' }, 'EXPIRED': { id: 'Kedaluwarsa', en: 'Expired' }, 'WAITING': { id: 'Menunggu', en: 'Waiting' }, 'IN_PROGRESS': { id: 'Sedang diproses', en: 'In progress' }, 'COMPLETED': { id: 'Selesai', en: 'Completed' }, 'CANCELED': { id: 'Dibatalkan', en: 'Canceled' }, 'CASH': { id: 'Tunai', en: 'Cash' }, 'BANK_TRANSFER': { id: 'Transfer bank', en: 'Bank transfer' }, 'WALLET': { id: 'Dompet digital', en: 'Wallet' }, 'QRIS': { id: 'QRIS', en: 'QRIS' },
  'For example, Main Store': { id: 'Contoh, Toko Utama', en: 'For example, Main Store' },
  'For example, Central Jakarta': { id: 'Contoh, Jakarta Pusat', en: 'For example, Central Jakarta' },
  'For example, Store Manager': { id: 'Contoh, Manajer Toko', en: 'For example, Store Manager' },
  'For example, Coffee Latte': { id: 'Contoh, Kopi Latte', en: 'For example, Coffee Latte' },
  'Add an optional description for this item': { id: 'Tambahkan deskripsi opsional untuk item ini', en: 'Add an optional description for this item' },
  'For example, 100000': { id: 'Contoh, 100000', en: 'For example, 100000' },
  'Select the date the price takes effect': { id: 'Pilih tanggal mulai berlaku harga', en: 'Select the date the price takes effect' },
};

export type BackofficeMessageKey = keyof (typeof messages)['id'];

interface BackofficeLocalizationValue {
  locale: BackofficeLocale;
  setLocale: (locale: BackofficeLocale) => void;
  t: (key: BackofficeMessageKey) => string;
  copy: (value: string) => string;
  formatDate: (value: Date, options?: Intl.DateTimeFormatOptions) => string;
  formatMoney: (amount: string, currency: string) => string;
}

const BackofficeLocalizationContext = createContext<BackofficeLocalizationValue | null>(null);

export function readStoredBackofficeLocale(): BackofficeLocale {
  if (typeof window === 'undefined') return 'id';
  return window.localStorage.getItem(storageKey) === 'en' ? 'en' : 'id';
}

export function BackofficeLocalizationProvider({ children }: { children: ReactNode }) {
  const [locale, setCurrentLocale] = useState<BackofficeLocale>(readStoredBackofficeLocale);
  const setLocale = useCallback((nextLocale: BackofficeLocale) => {
    window.localStorage.setItem(storageKey, nextLocale);
    setCurrentLocale(nextLocale);
  }, []);
  const value = useMemo<BackofficeLocalizationValue>(() => ({
    locale,
    setLocale,
    t: (key) => messages[locale][key],
    copy: (value) => copy[value]?.[locale] ?? value,
    formatDate: (value, options) => new Intl.DateTimeFormat(locale === 'id' ? 'id-ID' : 'en-US', options).format(value),
    formatMoney: (amount, currency) => new Intl.NumberFormat(locale === 'id' ? 'id-ID' : 'en-US', { style: 'currency', currency, maximumFractionDigits: 0 }).format(Number(amount)),
  }), [locale, setLocale]);
  return <BackofficeLocalizationContext.Provider value={value}>{children}</BackofficeLocalizationContext.Provider>;
}

export function useBackofficeLocalization(): BackofficeLocalizationValue {
  const context = useContext(BackofficeLocalizationContext);
  if (!context) throw new Error('BackofficeLocalizationProvider is missing.');
  return context;
}
