import { readStoredBackofficeLocale } from '../../app/localization/backoffice-localization';

const copy = {
  id: {
    pageEyebrow: 'Manajemen pelanggan',
    pageTitle: 'Member',
    pageDescription: 'Kelola pendaftaran member, status, dan riwayat poin.',
    searchPlaceholder: 'Cari nomor member, nama, atau no. HP...',
    empty: 'Tidak ada member yang cocok.',
    all: 'Semua',
    memberNumber: 'Nomor Member',
    customer: 'Pelanggan',
    phone: 'No. HP',
    status: 'Status',
    active: 'Aktif',
    inactive: 'Nonaktif',
    enroll: 'Daftarkan Member',
    import: 'Import Member',
    viewDetails: 'Lihat detail',
    editCustomer: 'Edit pelanggan',
    deactivate: 'Nonaktifkan member',
    activate: 'Aktifkan member',
    deactivateTitle: 'Nonaktifkan member?',
    activateTitle: 'Aktifkan member?',
    deactivateConfirm: 'Nonaktifkan',
    activateConfirm: 'Aktifkan',
    statusMessage: 'Ini hanya mengubah ketersediaan membership; riwayat poin tidak berubah.',
    statusUpdated: 'Status member diperbarui.',
    cancel: 'Batal',
    close: 'Tutup',
    save: 'Simpan',
    // Editor
    enrollTitle: 'Daftarkan Member',
    editTitle: 'Edit Pelanggan',
    memberIdentity: 'Identitas Member',
    memberIdentityHint: 'Nomor member dibuat otomatis oleh sistem saat disimpan.',
    customerData: 'Data Pelanggan',
    customerDataEnrollHint: 'Member baru hanya membutuhkan nama dan nomor HP.',
    customerDataEditHint: 'Perubahan berlaku untuk data pelanggan kanonis member ini.',
    name: 'Nama',
    namePlaceholder: 'Contoh: Ayu Lestari',
    phoneHint: 'Contoh: 081234567890',
    phoneInvalid: 'Masukkan nomor HP yang valid, contoh 081234567890.',
    joined: 'Bergabung',
    // Detail
    detailTitle: 'Detail Member',
    loadingDetail: 'Memuat detail member…',
    membership: 'Membership',
    joinedAt: 'Tanggal Bergabung',
    loyalty: 'Poin Loyalty',
    pointBalance: 'Saldo poin',
    pointHistory: 'Riwayat Poin',
    noPointHistory: 'Belum ada riwayat poin.',
    balanceAfter: 'Saldo',
    // Import
    importTitle: 'Import Member',
    importIntro:
      'Pindahkan data member dari sistem sebelumnya menggunakan template Excel. Poin loyalty tidak ikut diimpor.',
    downloadTemplate: 'Unduh template',
    templateHint: 'Isi sheet "Members". No. HP cukup ditulis 08…, tanpa +62.',
    chooseFile: 'Pilih file .xlsx',
    replaceFile: 'Ganti file',
    dropHint: 'Hanya file Excel .xlsx, maksimal 2 MB dan 1.000 member.',
    fileTypeInvalid: 'Pilih file Excel dengan format .xlsx.',
    fileTooLarge: 'Ukuran file maksimal 2 MB.',
    fileEmpty: 'File kosong.',
    validate: 'Validasi',
    validating: 'Memvalidasi…',
    back: 'Kembali',
    importAction: 'Import',
    importing: 'Mengimpor…',
    done: 'Selesai',
    totalRows: 'Total baris',
    validRows: 'Valid',
    errorRows: 'Error',
    warningRows: 'Peringatan',
    previewTitle: 'Pratinjau Import',
    previewErrorsHint: 'Perbaiki baris bertanda error di file, lalu validasi ulang.',
    previewReadyHint: 'Semua baris valid. Import akan menyimpan semua baris sekaligus.',
    previewLimited: (shown: number, total: number) =>
      `Menampilkan ${shown} dari ${total} baris; baris bermasalah ditampilkan lebih dulu.`,
    rejectedAtImport:
      'Data berubah sejak validasi. Tidak ada data yang disimpan; periksa baris berikut.',
    row: 'Baris',
    result: 'Hasil',
    autoNumber: 'Otomatis',
    importTime: 'Waktu import',
    actionCreate: 'Member & pelanggan baru',
    actionEnroll: 'Pelanggan lama jadi member',
    successTitle: 'Import berhasil',
    summaryImported: 'Member diimpor',
    summaryCreated: 'Pelanggan baru',
    summaryEnrolled: 'Pelanggan lama didaftarkan',
    summaryGenerated: 'Nomor member otomatis',
    summaryPreserved: 'Nomor member lama dipertahankan',
    templateFailed: 'Template tidak dapat diunduh.',
  },
  en: {
    pageEyebrow: 'Customer management',
    pageTitle: 'Members',
    pageDescription: 'Manage member enrollment, status, and loyalty history.',
    searchPlaceholder: 'Search member number, name, or phone...',
    empty: 'No matching members found.',
    all: 'All',
    memberNumber: 'Member number',
    customer: 'Customer',
    phone: 'Phone',
    status: 'Status',
    active: 'Active',
    inactive: 'Inactive',
    enroll: 'Enroll member',
    import: 'Import members',
    viewDetails: 'View details',
    editCustomer: 'Edit customer',
    deactivate: 'Deactivate member',
    activate: 'Activate member',
    deactivateTitle: 'Deactivate member?',
    activateTitle: 'Activate member?',
    deactivateConfirm: 'Deactivate',
    activateConfirm: 'Activate',
    statusMessage: 'This changes membership availability only; loyalty history remains unchanged.',
    statusUpdated: 'Membership status updated.',
    cancel: 'Cancel',
    close: 'Close',
    save: 'Save',
    enrollTitle: 'Enroll member',
    editTitle: 'Edit customer',
    memberIdentity: 'Member identity',
    memberIdentityHint: 'The member number is generated automatically when saved.',
    customerData: 'Customer data',
    customerDataEnrollHint: 'A new member needs only a name and a phone number.',
    customerDataEditHint: "Changes apply to this member's canonical customer profile.",
    name: 'Name',
    namePlaceholder: 'For example: Ayu Lestari',
    phoneHint: 'For example: 081234567890',
    phoneInvalid: 'Enter a valid phone number, for example 081234567890.',
    joined: 'Joined',
    detailTitle: 'Member detail',
    loadingDetail: 'Loading member details…',
    membership: 'Membership',
    joinedAt: 'Joined date',
    loyalty: 'Loyalty points',
    pointBalance: 'Point balance',
    pointHistory: 'Point history',
    noPointHistory: 'No point history yet.',
    balanceAfter: 'Balance',
    importTitle: 'Import members',
    importIntro:
      'Move members from a previous system with the Excel template. Loyalty points are not imported.',
    downloadTemplate: 'Download template',
    templateHint: 'Fill the "Members" sheet. Phone numbers can be written as 08…, without +62.',
    chooseFile: 'Choose .xlsx file',
    replaceFile: 'Replace file',
    dropHint: 'Excel .xlsx only, up to 2 MB and 1,000 members.',
    fileTypeInvalid: 'Choose an Excel .xlsx file.',
    fileTooLarge: 'The file must be at most 2 MB.',
    fileEmpty: 'The file is empty.',
    validate: 'Validate',
    validating: 'Validating…',
    back: 'Back',
    importAction: 'Import',
    importing: 'Importing…',
    done: 'Done',
    totalRows: 'Total rows',
    validRows: 'Valid',
    errorRows: 'Errors',
    warningRows: 'Warnings',
    previewTitle: 'Import preview',
    previewErrorsHint: 'Fix the rows marked with errors in the file, then validate again.',
    previewReadyHint: 'All rows are valid. Import saves every row together.',
    previewLimited: (shown: number, total: number) =>
      `Showing ${shown} of ${total} rows; rows with problems are listed first.`,
    rejectedAtImport: 'Data changed since validation. Nothing was saved; review the rows below.',
    row: 'Row',
    result: 'Result',
    autoNumber: 'Automatic',
    importTime: 'Import time',
    actionCreate: 'New member & customer',
    actionEnroll: 'Existing customer enrolled',
    successTitle: 'Import completed',
    summaryImported: 'Members imported',
    summaryCreated: 'New customers',
    summaryEnrolled: 'Existing customers enrolled',
    summaryGenerated: 'Generated member numbers',
    summaryPreserved: 'Preserved member numbers',
    templateFailed: 'The template could not be downloaded.',
  },
} as const;

export type MembershipCopy = (typeof copy)['id'] | (typeof copy)['en'];

export function membershipCopy(): MembershipCopy {
  return copy[readStoredBackofficeLocale()];
}

/** Indonesian wording for Runtime import issue codes; other codes fall back to Runtime's message. */
const importIssueCopy: Record<string, string> = {
  NAME_REQUIRED: 'Nama wajib diisi.',
  NAME_INVALID: 'Nama maksimal 160 karakter.',
  PHONE_REQUIRED: 'No. HP wajib diisi.',
  PHONE_INVALID: 'No. HP tidak valid, contoh 081234567890.',
  PHONE_DUPLICATE_IN_FILE: 'No. HP yang sama juga ada di baris {rows}.',
  PHONE_MEMBER_EXISTS: 'No. HP ini sudah dipakai member lain.',
  CUSTOMER_AMBIGUOUS:
    'Ada lebih dari satu pelanggan dengan No. HP ini. Rapikan data pelanggan terlebih dahulu.',
  MEMBER_NUMBER_TOO_LONG: 'Nomor member maksimal 32 karakter.',
  MEMBER_NUMBER_INVALID: 'Nomor member tidak valid.',
  MEMBER_NUMBER_DUPLICATE_IN_FILE: 'Nomor member yang sama juga ada di baris {rows}.',
  MEMBER_NUMBER_IN_USE: 'Nomor member ini sudah dipakai member lain.',
  MEMBER_NUMBER_OUT_OF_RANGE: 'Nomor member di luar rentang penomoran otomatis.',
  STATUS_INVALID: 'Status harus ACTIVE atau INACTIVE.',
  JOINED_AT_INVALID: 'Tanggal bergabung harus berformat YYYY-MM-DD, contoh 2024-01-31.',
  JOINED_AT_IN_FUTURE: 'Tanggal bergabung tidak boleh di masa depan.',
  FORMULA_NOT_ALLOWED: 'Rumus tidak diimpor; ketik nilainya langsung.',
  VALUE_UNREADABLE: 'Isi sel tidak dapat dibaca.',
  EXISTING_CUSTOMER_ENROLLED: 'Pelanggan yang sudah ada dengan No. HP ini akan dijadikan member.',
  EXISTING_CUSTOMER_NAME_KEPT: 'Nama di file berbeda; nama pelanggan yang sudah ada tetap dipakai.',
};

export function memberImportIssueText(issue: {
  code: string;
  message: string;
  relatedRows?: number[];
}): string {
  if (readStoredBackofficeLocale() !== 'id') return issue.message;
  const text = importIssueCopy[issue.code];
  return text ? text.replace('{rows}', (issue.relatedRows ?? []).join(', ')) : issue.message;
}
