import { readStoredBackofficeLocale } from '../../app/localization/backoffice-localization';

const copy = {
  id: {
    pageEyebrow: 'Manajemen pelanggan',
    pageTitle: 'Member',
    pageDescription: 'Kelola pendaftaran member, status, dan riwayat poin.',
    searchPlaceholder: 'Cari nomor member, nama, atau no. HP...',
    empty: 'Tidak ada member yang cocok.',
    all: 'Semua',
    memberNumber: 'Nomor Member',
    customer: 'Pelanggan',
    phone: 'No. HP',
    status: 'Status',
    active: 'Aktif',
    inactive: 'Nonaktif',
    enroll: 'Daftarkan Member',
    import: 'Import Member',
    viewDetails: 'Lihat detail',
    editCustomer: 'Edit pelanggan',
    deactivate: 'Nonaktifkan member',
    activate: 'Aktifkan member',
    deactivateTitle: 'Nonaktifkan member?',
    activateTitle: 'Aktifkan member?',
    deactivateConfirm: 'Nonaktifkan',
    activateConfirm: 'Aktifkan',
    statusMessage: 'Ini hanya mengubah ketersediaan membership; riwayat poin tidak berubah.',
    statusUpdated: 'Status member diperbarui.',
    cancel: 'Batal',
    close: 'Tutup',
    save: 'Simpan',
    // Editor
    enrollTitle: 'Daftarkan Member',
    editTitle: 'Edit Pelanggan',
    memberIdentity: 'Identitas Member',
    memberIdentityHint: 'Nomor member dibuat otomatis oleh sistem saat disimpan.',
    customerData: 'Data Pelanggan',
    customerDataEnrollHint: 'Member baru hanya membutuhkan nama dan nomor HP.',
    customerDataEditHint: 'Perubahan berlaku untuk data pelanggan kanonis member ini.',
    name: 'Nama',
    namePlaceholder: 'Contoh: Ayu Lestari',
    phoneHint: 'Contoh: 081234567890',
    phoneInvalid: 'Masukkan nomor HP yang valid, contoh 081234567890.',
    joined: 'Bergabung',
    // Detail
    detailTitle: 'Detail Member',
    loadingDetail: 'Memuat detail member…',
    membership: 'Membership',
    joinedAt: 'Tanggal Bergabung',
    loyalty: 'Poin Loyalty',
    pointBalance: 'Saldo poin',
    pointHistory: 'Riwayat Poin',
    noPointHistory: 'Belum ada riwayat poin.',
    balanceAfter: 'Saldo',
    // Import
    importTitle: 'Import Member',
    importIntro:
      'Pindahkan data member dari sistem sebelumnya menggunakan template Excel. Saldo poin lama dapat diisi di kolom Poin Awal. Jika No. HP sudah menjadi member, poin pada file ditambahkan ke saldonya dan data member tidak diubah.',
    downloadTemplate: 'Unduh template',
    templateHint: 'Isi sheet "Members". No. HP cukup ditulis 08…, tanpa +62.',
    chooseFile: 'Pilih file .xlsx',
    replaceFile: 'Ganti file',
    dropHint: 'Hanya file Excel .xlsx, maksimal 2 MB dan 1.000 member.',
    fileTypeInvalid: 'Pilih file Excel dengan format .xlsx.',
    fileTooLarge: 'Ukuran file maksimal 2 MB.',
    fileEmpty: 'File kosong.',
    validate: 'Validasi',
    validating: 'Memvalidasi…',
    back: 'Kembali',
    importAction: 'Import',
    importing: 'Mengimpor…',
    done: 'Selesai',
    totalRows: 'Total baris',
    validRows: 'Valid',
    errorRows: 'Error',
    warningRows: 'Peringatan',
    previewTitle: 'Pratinjau Import',
    previewErrorsHint: 'Perbaiki baris bertanda error di file, lalu validasi ulang.',
    previewReadyHint: 'Semua baris valid. Import akan menyimpan semua baris sekaligus.',
    previewLimited: (shown: number, total: number) =>
      `Menampilkan ${shown} dari ${total} baris; baris bermasalah ditampilkan lebih dulu.`,
    rejectedAtImport:
      'Data berubah sejak validasi. Tidak ada data yang disimpan; periksa baris berikut.',
    row: 'Baris',
    result: 'Hasil',
    autoNumber: 'Otomatis',
    importTime: 'Waktu import',
    openingPoints: 'Poin Awal',
    openingPointsUnavailable:
      'Poin Awal memerlukan fitur Poin Loyalty dan izin mengelola Loyalty. Kosongkan kolom tersebut atau isi 0.',
    actionCreate: 'Member & pelanggan baru',
    actionEnroll: 'Pelanggan lama jadi member',
    successTitle: 'Import berhasil',
    summaryImported: 'Member diimpor',
    summaryCreated: 'Pelanggan baru',
    summaryEnrolled: 'Pelanggan lama didaftarkan',
    summaryGenerated: 'Nomor member otomatis',
    summaryPreserved: 'Nomor member lama dipertahankan',
    summaryOpeningMembers: 'Member dengan saldo awal',
    summaryOpeningPoints: 'Total poin awal',
    ledgerOpeningBalance: 'Saldo awal migrasi',
    templateFailed: 'Template tidak dapat diunduh.',
    // Manual point adjustment
    adjustPoints: 'Sesuaikan poin',
    adjustType: 'Jenis penyesuaian',
    adjustAdd: 'Tambah poin',
    adjustSubtract: 'Kurangi poin',
    adjustAmount: 'Jumlah poin',
    adjustAmountPlaceholder: 'Contoh: 200',
    adjustAmountInvalid: 'Masukkan jumlah poin lebih dari 0.',
    adjustReason: 'Alasan',
    adjustReasonPlaceholder: 'Contoh: Poin dari sistem lama belum tercatat',
    adjustCurrent: 'Saat ini',
    adjustAdjustment: 'Penyesuaian',
    adjustResult: 'Hasil',
    adjustNegative: 'Pengurangan melebihi saldo poin. Saldo tidak boleh negatif.',
    adjustAppendOnly:
      'Penyesuaian dicatat sebagai riwayat baru beserta alasan dan pencatatnya. Riwayat poin yang sudah ada tidak diubah.',
    adjustSubmit: 'Simpan penyesuaian',
    adjustSaved: 'Poin member disesuaikan.',
    adjustLoadingBalance: 'Memuat saldo poin…',
    ledgerImportPoints: 'Poin dari import',
    ledgerManualAdjustment: 'Penyesuaian manual',
    ledgerReason: 'Alasan',
    // Opening points on enrollment
    openingPointsField: 'Poin awal (opsional)',
    openingPointsFieldHint:
      'Untuk member lama yang belum tercatat. Dicatat sebagai riwayat saldo awal; kosongkan jika tidak ada.',
    openingPointsFieldInvalid: 'Masukkan angka poin, contoh 1250.',
    // Import preview
    badgeExistingMember: 'Member sudah ada',
    pointsCurrent: 'Saat ini',
    pointsFromImport: 'Dari import',
    pointsResult: 'Hasil',
    summaryExistingMembers: 'Member lama ditambah poin',
    summaryExistingPoints: 'Poin ditambahkan ke member lama',
  },
  en: {
    pageEyebrow: 'Customer management',
    pageTitle: 'Members',
    pageDescription: 'Manage member enrollment, status, and loyalty history.',
    searchPlaceholder: 'Search member number, name, or phone...',
    empty: 'No matching members found.',
    all: 'All',
    memberNumber: 'Member number',
    customer: 'Customer',
    phone: 'Phone',
    status: 'Status',
    active: 'Active',
    inactive: 'Inactive',
    enroll: 'Enroll member',
    import: 'Import members',
    viewDetails: 'View details',
    editCustomer: 'Edit customer',
    deactivate: 'Deactivate member',
    activate: 'Activate member',
    deactivateTitle: 'Deactivate member?',
    activateTitle: 'Activate member?',
    deactivateConfirm: 'Deactivate',
    activateConfirm: 'Activate',
    statusMessage: 'This changes membership availability only; loyalty history remains unchanged.',
    statusUpdated: 'Membership status updated.',
    cancel: 'Cancel',
    close: 'Close',
    save: 'Save',
    enrollTitle: 'Enroll member',
    editTitle: 'Edit customer',
    memberIdentity: 'Member identity',
    memberIdentityHint: 'The member number is generated automatically when saved.',
    customerData: 'Customer data',
    customerDataEnrollHint: 'A new member needs only a name and a phone number.',
    customerDataEditHint: "Changes apply to this member's canonical customer profile.",
    name: 'Name',
    namePlaceholder: 'For example: Ayu Lestari',
    phoneHint: 'For example: 081234567890',
    phoneInvalid: 'Enter a valid phone number, for example 081234567890.',
    joined: 'Joined',
    detailTitle: 'Member detail',
    loadingDetail: 'Loading member details…',
    membership: 'Membership',
    joinedAt: 'Joined date',
    loyalty: 'Loyalty points',
    pointBalance: 'Point balance',
    pointHistory: 'Point history',
    noPointHistory: 'No point history yet.',
    balanceAfter: 'Balance',
    importTitle: 'Import members',
    importIntro:
      'Move members from a previous system with the Excel template. Previous point balances can be entered in the Poin Awal column. If a phone number already belongs to a member, the points in the file are added to its balance and the member data is not changed.',
    downloadTemplate: 'Download template',
    templateHint: 'Fill the "Members" sheet. Phone numbers can be written as 08…, without +62.',
    chooseFile: 'Choose .xlsx file',
    replaceFile: 'Replace file',
    dropHint: 'Excel .xlsx only, up to 2 MB and 1,000 members.',
    fileTypeInvalid: 'Choose an Excel .xlsx file.',
    fileTooLarge: 'The file must be at most 2 MB.',
    fileEmpty: 'The file is empty.',
    validate: 'Validate',
    validating: 'Validating…',
    back: 'Back',
    importAction: 'Import',
    importing: 'Importing…',
    done: 'Done',
    totalRows: 'Total rows',
    validRows: 'Valid',
    errorRows: 'Errors',
    warningRows: 'Warnings',
    previewTitle: 'Import preview',
    previewErrorsHint: 'Fix the rows marked with errors in the file, then validate again.',
    previewReadyHint: 'All rows are valid. Import saves every row together.',
    previewLimited: (shown: number, total: number) =>
      `Showing ${shown} of ${total} rows; rows with problems are listed first.`,
    rejectedAtImport: 'Data changed since validation. Nothing was saved; review the rows below.',
    row: 'Row',
    result: 'Result',
    autoNumber: 'Automatic',
    importTime: 'Import time',
    openingPoints: 'Opening points',
    openingPointsUnavailable:
      'Opening points need Loyalty Points and permission to manage Loyalty. Leave the Poin Awal column blank or 0.',
    actionCreate: 'New member & customer',
    actionEnroll: 'Existing customer enrolled',
    successTitle: 'Import completed',
    summaryImported: 'Members imported',
    summaryCreated: 'New customers',
    summaryEnrolled: 'Existing customers enrolled',
    summaryGenerated: 'Generated member numbers',
    summaryPreserved: 'Preserved member numbers',
    summaryOpeningMembers: 'Members with opening balance',
    summaryOpeningPoints: 'Total opening points',
    ledgerOpeningBalance: 'Migrated opening balance',
    templateFailed: 'The template could not be downloaded.',
    adjustPoints: 'Adjust points',
    adjustType: 'Adjustment type',
    adjustAdd: 'Add points',
    adjustSubtract: 'Subtract points',
    adjustAmount: 'Points',
    adjustAmountPlaceholder: 'For example: 200',
    adjustAmountInvalid: 'Enter a number of points greater than 0.',
    adjustReason: 'Reason',
    adjustReasonPlaceholder: 'For example: Points from the previous system were not recorded',
    adjustCurrent: 'Current',
    adjustAdjustment: 'Adjustment',
    adjustResult: 'Result',
    adjustNegative: 'The subtraction exceeds the point balance. The balance cannot go negative.',
    adjustAppendOnly:
      'The adjustment is recorded as a new history entry with its reason and author. Existing point history is not changed.',
    adjustSubmit: 'Save adjustment',
    adjustSaved: 'Member points adjusted.',
    adjustLoadingBalance: 'Loading point balance…',
    ledgerImportPoints: 'Imported points',
    ledgerManualAdjustment: 'Manual adjustment',
    ledgerReason: 'Reason',
    openingPointsField: 'Opening points (optional)',
    openingPointsFieldHint:
      'For a legacy member not recorded yet. Saved as an opening balance entry; leave blank for none.',
    openingPointsFieldInvalid: 'Enter a number of points, for example 1250.',
    badgeExistingMember: 'Existing member',
    pointsCurrent: 'Current',
    pointsFromImport: 'From import',
    pointsResult: 'Result',
    summaryExistingMembers: 'Existing members given points',
    summaryExistingPoints: 'Points added to existing members',
  },
} as const;

export type MembershipCopy = (typeof copy)['id'] | (typeof copy)['en'];

export function membershipCopy(): MembershipCopy {
  return copy[readStoredBackofficeLocale()];
}

/** Indonesian wording for Runtime import issue codes; other codes fall back to Runtime's message. */
const importIssueCopy: Record<string, string> = {
  NAME_REQUIRED: 'Nama wajib diisi.',
  NAME_INVALID: 'Nama maksimal 160 karakter.',
  PHONE_REQUIRED: 'No. HP wajib diisi.',
  PHONE_INVALID: 'No. HP tidak valid, contoh 081234567890.',
  PHONE_DUPLICATE_IN_FILE: 'No. HP yang sama juga ada di baris {rows}.',
  PHONE_MEMBER_EXISTS: 'No. HP ini sudah dipakai member lain.',
  EXISTING_MEMBER_DATA_DIFFERS:
    'Data pada file berbeda dengan data member saat ini. Data member yang sudah ada akan dipertahankan.',
  EXISTING_MEMBER_INACTIVE: 'Member ini nonaktif; poin tetap ditambahkan.',
  IMPORT_FILE_ALREADY_APPLIED:
    'File ini sudah pernah diimpor. Mengimpor ulang akan menambahkan poin dua kali.',
  CUSTOMER_AMBIGUOUS:
    'Ada lebih dari satu pelanggan dengan No. HP ini. Rapikan data pelanggan terlebih dahulu.',
  MEMBER_NUMBER_TOO_LONG: 'Nomor member maksimal 32 karakter.',
  MEMBER_NUMBER_INVALID: 'Nomor member tidak valid.',
  MEMBER_NUMBER_DUPLICATE_IN_FILE: 'Nomor member yang sama juga ada di baris {rows}.',
  MEMBER_NUMBER_IN_USE: 'Nomor member ini sudah dipakai member lain.',
  MEMBER_NUMBER_OUT_OF_RANGE: 'Nomor member di luar rentang penomoran otomatis.',
  STATUS_INVALID: 'Status harus ACTIVE atau INACTIVE.',
  JOINED_AT_INVALID: 'Tanggal bergabung harus berformat YYYY-MM-DD, contoh 2024-01-31.',
  JOINED_AT_IN_FUTURE: 'Tanggal bergabung tidak boleh di masa depan.',
  FORMULA_NOT_ALLOWED: 'Rumus tidak diimpor; ketik nilainya langsung.',
  VALUE_UNREADABLE: 'Isi sel tidak dapat dibaca.',
  OPENING_POINTS_INVALID: 'Poin Awal harus berupa angka, contoh 1250 atau 1250.5.',
  OPENING_POINTS_NEGATIVE: 'Poin Awal tidak boleh negatif.',
  OPENING_POINTS_TOO_PRECISE: 'Poin Awal maksimal 4 angka desimal.',
  OPENING_POINTS_TOO_LARGE: 'Poin Awal terlalu besar.',
  LOYALTY_OPENING_BALANCE_NOT_AVAILABLE:
    'Fitur Poin Loyalty tidak aktif; kosongkan Poin Awal atau isi 0.',
  LOYALTY_OPENING_BALANCE_NOT_PERMITTED: 'Import Poin Awal memerlukan izin mengelola Loyalty.',
  EXISTING_CUSTOMER_ENROLLED: 'Pelanggan yang sudah ada dengan No. HP ini akan dijadikan member.',
  EXISTING_CUSTOMER_NAME_KEPT: 'Nama di file berbeda; nama pelanggan yang sudah ada tetap dipakai.',
};

export function memberImportIssueText(issue: {
  code: string;
  message: string;
  relatedRows?: number[];
}): string {
  if (readStoredBackofficeLocale() !== 'id') return issue.message;
  const text = importIssueCopy[issue.code];
  return text ? text.replace('{rows}', (issue.relatedRows ?? []).join(', ')) : issue.message;
}
